== Level 1 immutability

Let us start with a definition:

****
*Definition*: We say a field is *effectively final* when it either has the modifier `final`, or it is not assigned to in methods that can be transitively called from non-private (non-constructor) methods.
****

The code analyser annotates with `@Final` in the latter case; there is no point in cluttering with an annotation when the modifier is already there.
It annotates fields that are not effectively final with `@Variable`.

This definition allows effectively final fields to be assigned in methods accessible only from the constructor:

.Example 1, effectively final, but not with the `final` modifier
[source,java]
----
class EffectivelyFinal1 {
    @Final
    private Random random;

    public EffectivelyFinal1() {
        initialize(3L);
    }

    private void initialize(long seed) {
        random = new Random(seed);
    }

    // no methods access initialize()

    public int nextInt() {
        return random.nextInt();
    }
}
----

Obviously, if the same method is also accessible after construction, the field becomes variable:

.Example 2, the method setting the field is accessible after construction
[source,java]
----
class EffectivelyFinal2 {
    @Variable
    private Random random;

    public EffectivelyFinal2() {
        reset();
    }

    public void reset() {
        initialize(3L);
    }

    private void initialize(long seed) {
        random = new Random(seed);
    }

    public int nextInt() {
        return random.nextInt();
    }
}
----

Note that it is perfectly possible to rewrite the first example in such a way that the `final` modifier can be used.
From the point of view of the code analyser, this does not matter.
The wider definition will allow for more situations to be recognized for what they really are.

When an object consists solely of primitives, or deeply immutable objects such as `java.lang.String`, having all fields effectively final is sufficient to generate an object that is again deeply immutable.

.Example 3, an object consisting of primitives and a string.
[source,java]
----
class DeeplyImmutable1 {
    public final int x;
    public final int y;
    public final String message;

    public DeeplyImmutable1(int x, int y, String message) {
        this.message = message;
        this.x = x;
        this.y = y;
    }
}
----

.Example 4, another way of being effectively final
[source,java]
----
class DeeplyImmutable2 {
    @Final
    private int x;
    @Final
    private int y;
    @Final
    private String message;

    public DeeplyImmutable2(int x, int y, String message) {
        this.message = message;
        this.x = x;
        this.y = y;
    }

    public String getMessage() {
        return message;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }
}
----

Examples 3 and 4 are functionally equivalent: there is no way of changing the values of the fields once they have been set.
In the real world there may be a reason why someone requires the getters.
Or, you may be given code as in Example 2, but you are not allowed to change it.
Whatever the reason, the code analyser should recognize effective finality.

Note that we will not make a distinction between any of the different non-private access modes in Java.
Only the private modifier gives sufficient guarantees that no reassignment to the fields is possible.

We now have observed that for the purpose of defining immutability, having all your fields effectively final can be sufficient in certain circumstances.
We use this as the basis for the first level of immutability:

****
*Definition*: We call a type *effectively level 1 immutable* when all its fields are effectively final.
****

The code analyser annotates level 1 immutable types with `@E1Immutable`.
Types that are not `@E1Immutable` because they have at least one `@Variable` field, are annotated `@Mutable`.

As above with effective finality, the term _effective_ is present to make a distinction between formal immutability, and immutability that the code analyser computes.
It will also serve to distinguish from _eventual_ immutability, where (in this case) the finality will be achieved only after the code reaches a certain state.
More on this later, but here is a first example of an eventually level 1 immutable type:

.Simplified version of `SetOnce`
[source,java]
----
@E1Immutable(after="set")
class SetOnce<T> {
    private T t;

    @Mark("set")
    public void set(T t) {
        if(t == null) throw new NullPointerException();
        if(this.t == null) throw new UnsupportedOperationException("Already set");
        this.t = t;
    }

    @Only(after="set")
    public void get() {
        if(t == null) throw new UnsupportedOperationException("Not yet set");
        return t;
    }
}
----

Once a value has been set, the field `t` cannot be assigned anymore.

We have just observed that if one restricts to primitives and types like `java.lang.String`, level 1 immutability is sufficient to guarantee deep immutability.
It is not feasible (and we do not wish to) work only with deeply immutable objects.
Moreover, it is easy to see that level 1 immutability is not enough to guarantee what we intuitively may think immutability stands for:

.Example 5, level 1 immutability does not guarantee intuitive immutability
[source,java]
----
@E1Immutable
class StringsInArray {
    private final String[] data;
    public StringsInArray(String[] strings) {
        this.data = strings;
    }
    public String getFirst() {
        return data[0];
    }
}

...
String[] strings = { "a", "b" };
StringsInArray sia = new StringsInArray(strings);
Assert.assertEquals("a", sia.getFirst());
strings[0] = "c"; // <1>
Assert.assertEquals("c", sia.getFirst()); // <2>
----
<1> External modification of the array.
<2> As a consequence, the data structure has been modified.

To continue, we must first understand the notion of modification.
