== Containers

Loosely speaking, a container is a type to which you can safely pass on your objects, it will not modify them.
This is the formal rule:

****
*Definition*: a type is a *container* when no non-private method or constructor modifies its parameters.
****

Whatever else the container does, storing the parameters in fields or not, it will not change your objects.
You obviously remain free to change them elsewhere; then the container will hold on to the changed object, not some copy.

Containers are complementary to immutable objects, and we will find that many immutable objects are containers, while some containers are the precursors to immutable types.
There are two archetypes for containers: collections and builders.

The code analyser will annotate a type that is both level 1 immutable, and a container, with {e1container}.
This occurs frequently enough to justify a separate annotation.
The simple but useful utility type `Pair` trivially satisfies both requirements:

.A pair of objects
[source,java]
----
@E1Container
public class Pair<K,V> {
    public final K k;
    public final V v;
    public Pair(K k, V v) {
        this.k = k;
        this.v = v;
    }
    public K getK() {
        return k;
    }
    public V getV() {
        return v;
    }
}
----

While it is clearly level 1 immutable, it will remain to be seen if it satisfies all criteria for intuitive immutability.
However, it is easily recognized as a container: a type you use and trust to hold objects.

Containers occur frequently as static sub-types to build immutable objects.
Examples of these will follow later, after the definition of level 2 immutability.

Let us conclude this section with an example consisting of three types: the first a class computed to be a container, the second a container according to the contract, and the third a class which cannot be a container:

[source,java]
----
@Container
class ErrorMessage {
    private String message;

    public ErrorMessage(String message) {
        this.message = message;
    }

    @NotModified
    public String getMessage() {
        return message;
    }

    @Modified
    public void setMessage(String message) {
        this.message = message;
    }
}

@Container
interface ErrorRegistry {
    @NotModified
    List<ErrorMessage> getErrors();

    @Modified
    void addError(@NotModified ErrorMessage errorMessage); // <1>
}

class BinaryExpression extends Expression {
    public final Expression lhs;
    public final Expression rhs;

    // ...

    public void evaluate(@Modified ErrorRegistry errorRegistry) {
        // ...
        if(lhs instanceof NullConstant || rhs instanceof NullConstant) {
            errorRegistry.addError(new ErrorMessage(...)); // <2>
        }
        // ...
    }
}
----
<1> Implementations of `ErrorRegistry` will not be allowed to use the `setMessage` setter in `addError`.
<2> Here a modifying method call takes place.

The `BinaryExpression` class is not a container, because it uses one of the parameters of a public method, `errorRegistry` of `evaluate`, as a writable container.

// ensure a newline at the end
