[#linking-and-independence]
== Linking and independence

Let us now elaborate on how we will compute modifications, in a path towards level 2 immutability.
Consider the following example:

.Example 6, field linked to constructor parameter
[source,java]
----
class LinkExample1<X> {
    private final Set<X> set;

    public LinkExample1(Set<X> xs) {
        this.set = xs;
    }

    public void add(X x) {
        set.add(x);
    }
}
----

After construction, an instance of `LinkExample1` contains a reference to the set that was passed on as an argument to its constructor.
We say the field `set` links to the parameter `xs` of the constructor.
In this example, this is an expensive way of saying that there is an assignment from one to the other.
However, linking can become more complicated.

The {e2immu} analyser will add modification annotations to `LinkExample1` as follows:

.Example 7, field linked to constructor parameter, with annotations
[source,java]
----
class LinkExample1<X> {
    @Modified
    private final Set<X> set;

    public LinkExample1(@Modified Set<X> xs) {
        this.set = xs;
    }

    @Modified
    public void add(X x) {
        set.add(x);
    }
}
----

The parameter `x` of `LinkExample1.add` is {nm} because the first parameter of `Set.add` is {nm}.
The `add` method modifies the field, which causes the annotation first on the method, then on the field, and finally on the parameter of the constructor.
Because of the latter, `LinkExample1` cannot be marked {container}.

Linking looks at the underlying object, and not at the variable.
Consider the following alternative `add` method:

.Example 8, alternative add method
[source,java]
----
@Modified
public void add(X x) {
    Set<X> theSet = this.set;
    X theX = x;
    theSet.add(theX);
}
----

Nothing has changed, obviously.
Finally, as an example of how linking can become more complicated than following assignments, consider a typical _view_ on a collection:

.Example 9, linking using a method call
[source,java]
----
List<X> list = createSomeLargeList();
List<X> sub = list.subList(1, 5);
sub.set(0, x); // will modify sub, and list!
----

On the other side of the spectrum, linking does not work on objects that cannot be modified, like primitives or deeply immutable objects such as the primitives, or `java.lang.String`.

Let us summarize by:

****
Intuitively, linking two variables means that modifying the content of one variable implies that the content of the linked variable may be modified too.
****

We will discuss linking formally in <<linking-part2>>.
For now, assume that a field links to another field, or to a parameter, if there is a possibility that both variables represent (part of) the same object (their object graphs overlap).

The opposite of linking is independence.
While the code analyser will not express all the linking that goes on, it will annotate (in)dependence on the entry and exit points of the type: a method's return value and parameters, and a constructor's parameters.

****
*Definition*:
A method or constructor is *independent* when neither the parameters, nor the returned value (in case there is one, not `void`, not `this`) link to any of the fields of the type.
The independence (or dependence) is marked with {independent} (or {dependent}) on the method for the return value, and on the relevant parameters otherwise.
****

It follows immediately that:

* empty constructors of top-level types and static sub-types (but not necessarily inner classes, sub-types that are not static) are always independent;
* non-modifying methods that return primitives or deeply immutable objects are independent, since no assignments take place, and the returned objects cannot be modified.

Examples follow soon, once immutability has been defined in more detail.
We discuss the special case of (in)dependence in the context of parameters of types with abstract methods in <<functional-interfaces>>.

