== Level 2 immutability

=== Definition

First, what do we want intuitively?
A useful form of immutability, less strong than deeply immutable, but better than level 1 immutability for many situations.
We propose the following description:

****
After construction, an immutable type holds a number of objects; the type will not change their content, nor will it exchange these objects for other objects, or allow others to do so.
The type is not responsible for what others do to the content of the objects it was given.
****

Technically, level 2 immutability is much harder to define than level 1 immutability.
We identify three rules, on top of the obvious level 1 immutability requirement.
One of these must be observed at all times:

****
*Definition*: the *first rule of level 2 immutability* is that all fields must be {nm}.
****

Our friend the `Pair` satisfies this first rule:

[source,java]
----
public class Pair<K,V> {
    public final K k;
    public final V v;
    public Pair(K k, V v) {
        this.k = k;
        this.v = v;
    }
}
----

Note that since `K` and `V` are unbound generic types, it is not possible to modify their content from inside `Pair`, since there are no modifying methods one can call on unbound types.

How does it fit the intuitive rule for immutability?
The type `Pair` holds two objects.
The type does not change their content, nor will it exchange these two objects for others, or allow others to do so.
It is clear the users of `Pair` may be able to change the content of the objects they put in the `Pair`.
Summarizing: `Pair` fits the intuitive definition nicely.

Here is an example which shows the necessity of the first rule more explicitly:

.Point and Line
[#point-and-line]
[source,java]
----
@Container
class Point {
    @Variable
    private double x;

    @Variable
    private double y;

    @NotModified
    public double getX() {
        return x;
    }

    @Modified
    public void setX(double x) {
        this.x = x;
    }

    @NotModified
    public double getY() {
        return y;
    }

    @Modified
    public void setY(double y) {
        this.y = y;
    }
}

@E1Container
class Line {
    @Final
    @Modified
    private Point point1;

    @Final
    @Modified
    private Point point2;

    public Line(Point point1, Point point2) {
        this.point1 = point1;
        this.point2 = point2;
    }

    @NotModified
    public Point middle() {
        return new Point((point1.getX() + point2.getX())/2.0,
             (point1.getY()+point2.getY())/2.0);
    }

    @Modified
    public void translateHorizontally(double x) {
        point1.setX(point1.getX() + x); // <1>
        point2.setX(point2.getX() + x);
    }
}
----
<1> Modifying operation on `point1`.

The fields `point1` and `point2` are effectively final.
Without the translation method, the fields would be {nm} as well.
The translation method modifies their content, rendering the type not level 2 immutable.

Assuming a type's goal is to store a number of objects, it is easy to see that a level 1 immutable type cannot hold additional, modifiable state.
It follows that every method call on the container object with the same arguments will render the same result.
(Note that this cannot be bypassed by using _static_ state, i.e., state specific to the type rather than the object.
Our definitions make no distinction between static and instance fields.)

In order to hold an arbitrary (or even modestly large) amount of objects, a type has to have _support data_: think an array, a tree structure, buckets for a hash table, etc.
The rest of the definition of level 2 immutability is essentially about expressing the immutability of this support data.
After construction, a level 2 immutable type will still hold a fixed number of objects, and the type will not change their content, nor exchange them for other objects, nor allow others to exchange them.

We will introduce two additional rules to the definition of level 2 immutability.
They will only be of relevance for _some_ fields; requiring them for all fields results in too strong a definition, and we have seen higher up that there are situations where the first rule is sufficient.
Rather than specifying which fields need to follow the additional rules, it is easier to say which fields are exempt from them:

. fields that are of level 2 immutable type themselves;
. fields whose type can be replaced by an unbound type parameter.

Note that for all modification purposes we can replace unbound type parameters with `java.lang.Object`, which is level 2 immutable.
We will call those fields _implicitly immutable_, and the total of the values of fields of implicitly immutable type the _implicitly immutable content_ of the type.
Their primary characteristic is that their content is inaccessible from within the type

Constructor parameters of unbound type parameter, or method return types of unbound type parameter are always independent, in the same way that level 2 immutable types are: inside the class, there's no way of modifying them.

We now add rules 2 and 3 to the definition, and obtain:

****
*Definition: level 2 immutability*:

(*Rule 0*: The type is level 1 immutable: all fields are effectively final)

*Rule 1*: All fields are {nm}.

*Rule 2*: All fields are either private, or of level 2 immutable or implicitly immutable type.

*Rule 3*: All constructors and non-private methods are independent of the fields.
****

Rule 2 is there to ensure that the content of the object cannot be modified by means of access to the non-private fields.
Rule 3 ensures that the content of the object cannot be modified externally.

The first rule can be reached _eventually_ if there is one or more methods that effect a transition from the mutable to the immutable state.
This typically means that all methods that assign or modify fields become off-limits after calling this marker method.
Eventuality for rules 2 and 3 seems too far-fetched.
We address the topic of eventual immutability fully in the section <<eventual-immutability>>.

The section <<params-functional-interface>> will discuss modification and independence of functional interface types.

Let us go to examples immediately.

.Example with array, v1
[source,java]
----
class ArrayContainer1<T> {
    private final T[] data;
    public ArrayContainer1(T[] ts) {
        this.data = ts;
    }
    public Stream<T> stream() {
        return Arrays.stream(data);
    }
}
----

After creation, changes to the source array `ts` are effectively changes to the data array `data`.
This construct fails rule 3, independence.
Here the array of type `T[]` is the support data that holds `T`, which also appears in the return type of the `stream` method, held by `Stream`.

.Example with array, v2, still not OK
[source,java]
----
class ArrayContainer2<T> {
    public final T[] data;
    public ArrayContainer2(T[] ts) {
        this.data = new T[ts.length];
        System.arraycopy(ts, 0, data, 0, ts.length);
    }
    public Stream<T> stream() {
        return Arrays.stream(data);
    }
}
----

Users of this type can modify the content of the array using direct field access!
This construct fails rule 2, which applies for the same reasons as in the previous example.

.Example with array, v3, safe
[source,java]
----
class ArrayContainer3<T> {
    private final T[] data; // <1>
    public ArrayContainer3(T[] ts) {
        this.data = new T[ts.length]; // <2>
        System.arraycopy(ts, 0, data, 0, ts.length);
    }
    public Stream<T> stream() {
        return Arrays.stream(data);
    }
}
----
<1> The array is private, and therefore protected from external modification.
<2> The array has been copied, and therefore is independent of the one passed in the parameter.

The independence rule enforces the type to have its own structure rather than someone else's.
Here's the same group of examples, now with JDK Collections:

.Example with collection, v1
[source,java]
----
class SetBasedContainer1<T> {
    private final Set<T> data;
    public SetBasedContainer1(Set<T> ts) {
        this.data = ts; // <1>
    }
    public Stream<T> stream() {
        return data.stream();
    }
}
----
<1> After creation, changes to the source set are effectively changes to the data.

The lack of independence of the constructor violates rule 3 in the first example.

.Example with collection, v2, still not OK
[source,java]
----
class SetBasedContainer2<T> {
    public final Set<T> data; // <1>
    public SetBasedContainer2(Set<T> ts) {
        this.data = new HashSet<>(ts);
    }
    public Stream<T> stream() {
        return data.stream();
    }
}
----
<1> Users of this type can modify the content of the set after creation!

Here, the `data` field is public, which allows for external modification.

.Example with set, v3, safe
[source,java]
----
class SetBasedContainer3<T> {
    private final Set<T> data; // <1>
    public SetBasedContainer3(Set<T> ts) {
        this.data = new HashSet<>(ts); // <2>
    }
    public Stream<T> stream() {
        return data.stream();
    }
}
----
<1> The set is private, and therefore protected from external modification.
<2> The set has been copied, and therefore is independent of the one passed in the parameter.

Finally, we have a level 2 immutable type.

.Example with set, v4, safe
[source,java]
----
class SetBasedContainer4<T> {
    public final ImmutableSet<T> data; // <1>
    public SetBasedContainer4(Set<T> ts) {
        this.data = Set.copyOf(ts); // <2>
    }
    public Stream<T> stream() {
        return data.stream();
    }
}
----
<1> the data is public, but the `ImmutableSet` is {e2immutable} itself.
<2> Independence guaranteed.

The independence rule 3 is there to ensure that the type does not expose its support data through parameters and return types:

.Example with set, v5, unsafe
[source,java]
----
class SetBasedContainer5<T> {
    private final Set<T> data; // <1>
    public SetBasedContainer5(Set<T> ts) {
        this.data = new HashSet<>(ts); // <2>
    }
    public Set<T> getSet() {
        return data; // <3>
    }
}
----
<1> No exposure via the field
<2> No exposure via the parameter of the constructor
<3> ... but exposure via the getter.
We could as well have made the field `public final`.

Note that by decomposing all definitions, we observe that requiring all fields to be {final} and {nm} is equivalent to requiring that all non-private fields have the `final` modifier, and that methods that are not part of the construction phase, are {nm}.

The following type is {container}, the field is {final}, but it is not {nm}:

[source,java]
----
class Example2 {
    @Final
    @Modified
    public final Set<T> set = new HashSet<>();

    @Modified
    public void add(T t) { set.add(t); }

    @NotModified
    public Stream<T> stream() { return set.stream(); }
}
----

[#dynamic-type-annotations]
=== Dynamic type annotations

When it is clear a method returns an immutable set, but the formal type is `java.util.Set`, the {e2immutable} annotation can 'travel':

[source,java]
----
@E2Container
class SetBasedContainer6<T> {
    @E2Container
    public final Set<T> data;

    public SetBasedContainer4(Set<T> ts) {
        this.data = Set.copyOf(ts);
    }

    @E2Container
    public Set<T> getSet() {
        return data;
    }
}
----

Whilst `Set` in general is not {e2immutable}, the `data` field itself is.

The computations that the analyser needs to track dynamic type annotations, are similar to those it needs to compute eventual immutability.
We introduce them in the next chapter.

[#inheritance]
=== Inheritance

Deriving from a class that is level 2 immutable, is the most normal situation: since `java.lang.Object` is a level 2 immutable container, every class will do so.
Clearly, the property is not inherited.
Most importantly, the analyser prohibits changing the modification status of methods: once a method is non-modifying, it cannot become modifying in a derived class.
This means, for example, that the analyser will block a modifying `equals()` method!
Note that this rule applies to implementations of methods of all super-types: no implementation of `java.util.Collection.size()`
will be allowed to be modifying.

The guiding principle here is that of _consistency_ or _expectation_: software developers are expecting that `equals` is non-modifying.
They know that a setter will make an assignment, but they'll expect a getter to simply return a value.
No getter should ever be modifying.

The other direction is more interesting, while equally simple to explain: deriving from a parent class cannot increase the immutability level.
Explicitly changing a modifying method into a non-modifying one is not allowed by the analyser.

