[#eventual-immutability]
== Eventual immutability

There are many constraints on real-world use cases where immutability is not immediate.
The type then follows a life cycle described as create, use, drop.

Challenges:

* external frameworks insist on a way of working perpendicular to that of your project
* some graph-like data structures simply cannot be made immutable using conventional tools
* once you go eventually immutable, how is the propagation organized?

When possible, use a builder.

=== Builders

[source,java]
----
@E2Container
class Point {
    public final double x;
    public final double y;

    public Point(double x, double y) {
        this.x = x;
        this.y = y;
    }
}

@E2Container
class Polygon {

    public final List<Point> points;

    private Polygon(List<Point> points) { // <1>
        this.points = points;
    }

    @Container(builds=Polygon.class)
    static class Builder {
        private List<Point> points = new ArrayList<>();

        public void addPoint(Point point) {
            points.add(point);
        }

        public Polygon build() {
            return new Polygon(List.copyOf(points));
        }
    }
}
----
<1> The private constructor combined with the construction of an immutable copy in the `build` method guarantees level 2 immutability.

If your code can live with two different types (`Polygon.Builder`, `Polygon`) to represent polygons in their different stages (mutable, immutable), the builder paradigm is great.
If, on the other hand, you want to hold polygons in a type that spans both stages of the polygon lifecycle, it becomes difficult to do this with an eye on immutability.
One solution is the use of an interface that is implemented both by the builder and the immutable type.

The <<support-firstthen>> type can also assist in this situation: it holds an initial object (the _first_) until a state change occurs, and it is forced to hold a second object (the _then_).
Once it is in the final state, it cannot change anymore.
It is _eventually immutable_:

[source,java]
----
class PolygonManager {
    // initially, the polygon is in builder phase
    public final FirstThen<Polygon.Builder, Polygon> polygon =
        new FirstThen<>(new Polygon.Builder());

    // ...

    public void construct() {
        // in builder phase ...
        polygon.getFirst().add(point);
        // transition
        polygon.set(polygon.getFirst().build());
        // from here on, polygon is immutable!
    }

    public Point firstPoint() {
        return polygon.get().points.get(0);
    }
}
----

=== Definition

We propose a system of eventual immutability based on a single transition of state inside an object.

.First example of frozen class
[source,java]
----
@E2Container(after="frozen")
class SimpleImmutableSet1<T> {
    private final Set<T> set = new HashSet<>();
    private boolean frozen;

    @Only(before="frozen")
    public boolean add(T t) {
        if(frozen) throw new UnsupportedOperationException();
        set.add(t);
    }

    @Mark("frozen")
    public void freeze() {
        if(frozen) throw new UnsupportedOperationException();
        frozen = true;
    }

    @Only(after="frozen")
    public Stream<T> stream() {
        if(!frozen) throw new UnsupportedOperationException();
        return set.stream();
    }

    @TestMark("frozen")
    public boolean isFrozen() { // <1>
        return frozen;
    }

    public int size() { // <1>
        return set.size();
    }
}
----
<1> These methods can be called any time.

The analyser has no problem detecting the presence of preconditions, and observing that one method changes its own precondition.
The rules, however, are sufficiently general to support arbitrary preconditions, as shown in the following variant.
This example does not require an additional field, but relies on the empty/not-empty state change:

.Second example of frozen class
[source,java]
----
@E2Container(after="set")
class SimpleImmutableSet2<T> {
    private final Set<T> set = new HashSet<>();

    @Mark("set")
    public void initialize(Set<T> data) {
        if(!set.isEmpty()) throw new UnsupportedOperationException();
        if(data.isEmpty()) throw new IllegalArgumentException();
        set.addAll(data);
    }

    @Only(after="set")
    public Stream<T> stream() {
        if(set.isEmpty()) throw new UnsupportedOperationException();
        return set.stream();
    }

    public int size() {
        return set.size();
    }

    @TestMark("set")
    public boolean hasBeenInitialised() {
        return !set.isEmpty();
    }
}
----

Let us summarize the annotations:

* The {mark} annotation marks methods that change the state from _before_ to _after_.
* The {only} annotation identifies methods that, because of their precondition, can only be executed without raising an exception before (when complemented with a `before="..."` parameter) or after (with a `after="..."` parameter) the transition.
* The analyser computes the {testMark} annotation on methods which return the state as a boolean.
There is a parameter to indicate that instead of returning `true` when the object is _after_, the method actually returns `true` on _before_.
* Finally, the eventuality of the type shows in the `after="..."` parameter of {e1immutable}, {e2immutable} or their container versions.

In each of these annotations, the actual value of the `...` in the `after=` or `before=` parameters is the name of the field.

In case there are multiple fields involved, their names are represented in a comma-separated fashion.

The {mark} and {only} annotations can also be assigned to parameters, in the event that marked methods are called on a parameter of eventually immutable type.
Consider the following utility method for <<support-eventuallyfinal>>, frequently used in the analyser:

.Code fragment from EventuallyFinalExtension
[source,java]
----
public static <T> void setFinalAllowEquals(@Mark("isFinal") EventuallyFinal<T> eventuallyFinal, T t) {
    if (eventuallyFinal.isVariable() || !Objects.equals(eventuallyFinal.get(), t)) {
        eventuallyFinal.setFinal(t);
    }
}
----

Here, the `setFinal` method's {mark} annotation travels to the parameter, where it is applied to the argument each time the static method is applied.

=== Propagation

The support types detailed in <<support-classes>> can be used as building blocks to make ever more complex eventually immutable classes.
Effectively final fields of eventually immutable type will at some point hold objects that are in their final or `after` state, in which case they act as level 2 immutable fields.

The analyser itself consists of many eventually immutable classes; we show some examples in <<in-the-analyser>>.

IMPORTANT: For everyday use of eventual immutability, this is probably the most important consequence of all definitions up to now.

=== Before the mark

A method can return an eventually immutable object, guaranteed to be in its initial or `before` state.
This can be annotated with {beforeMark}.
Employing `SimpleImmutableSet1` from the example above,

[source,java]
----
@BeforeMark
public SimpleImmutableSet1 create() {
    return new SimpleImmutableSet1();
}
----

Similarly, the analyser can compute a parameter to be {beforeMark}, when in the method, at least one before-mark methods is called on the parameter.

Finally, a field can even be {beforeMark}, when it is created or arrives in the type as {beforeMark}, and stays in this state.
This situation must occur in a type with a {finalizer}, as explained in <<finalizers>>.

=== Extensions of annotations

When a type is eventually level 1 immutable, should the field(s) of the state transition be {variable} or {final}?
Similarly, when a type is eventually level 2 immutable, should the analyser mark the initially mutable or assignable fields {modified} or {nm}?

Basically, we propose to mark with the end state, qualifying with the parameter `after`:

[options=header]
|===
| property | not present | eventually | effectively
| finality of field | {variable} | `@Final(after="mark")` | {final}
| non-modification of field | {modified} | `@NotModified(after="mark")` | {nm}
|===

Since in an IDE it is not too easy to have multiple visual markers, it seems best to use the same visuals as the end state.

When a type is effectively level 1 immutable (not eventually), all fields are effectively final.
The analyser wants to emphasise the rules needed to obtain (eventual) level 2 immutability, by clearly indicating which fields break the level 2 immutability rules.
In the case of eventual level 2 immutability,

* modifications to the support data cease after a given mark
* the analyser disallows modifications to the other fields.

Eventual finality simply adds a  `@Final(after="mark")` annotation to each of these situations.

// ensure a newline at the end
