[#modification-part2]
== Modification, part2

This section goes deeper into modification, linking and independence.
We start with cyclic references.

=== Cyclic references

We need to study the situation of seemingly non-modifying methods with modifying parameters.
Up to now, a method is only modifying when it assigns to a field, calls a modifying method on one of the fields, or directly calls a modifying method on `this`.
However, there could be indirect modifications, as in:

.Indirect modifications
[source,java]
----
@E2Container
public class CyclicReferences {

    @MutableModifiesArguments
    static class C1 {

        @Variable
        private int i;

        @Modified
        public int incrementAndGet() {
            return ++i;
        }

        @Modified // <1>
        public int useC2(@Modified C2 c2) {
            return i + c2.incrementAndGetWithI();
        }

    }

    @E1Immutable
    static class C2 {

        private final int j;

        @Modified
        private final C1 c1;

        public C2(int j, @Modified C1 c1) {
            this.c1 = c1;
            this.j = j;
        }

        @Modified
        public int incrementAndGetWithI() {
            return c1.incrementAndGet() + j;
        }
    }
}
----
<1> `useC2` does not directly modify `i`, but `incrementAndGetWithI` does so indirectly.

This observation forces us to tighten the definition of a non-modifying method: on top of the definition given above, we have to ensure that none of the modifying methods called on a parameter which is {modified}, call one of 'our' modifying methods.
These rules are mostly, but not easily, enforceable when all code is visible.

An additional interface can help to remove the circular dependency between the types.
This has the advantage of simplicity, both for the programmer and the analyser, which at this point doesn't handle circular dependencies too well.
It imposes more annotation work on the programmer, however, because the interface's methods need contracting.

[#linking-formally]
=== Linking, formally

To compute linking, the analyser tries to track actual objects, with the aim of knowing if a field links to another field or a parameter.
It computes a dependency graph of variables depending on other variables, with the following four basic rules:

****
Rule 1: in an assignment `v = w`, variable `v` links to variable `w`.
****

****
Rule 2: in an assignment `v = a.method(b)`,`v` potentially links to `a` and `b`.
****

Note that saying `v` links to `a` is the same as saying that the return value of `method` links to some field inside `A`, the type of `a`.
This is especially clear when `a == this`.

We discern a number of special cases:

. When `v` is of primitive or {e2immutable} type, there cannot be any linking; `v` does not link to `a` nor `b`.
. If `b` is of primitive or {e2immutable} type, `v` cannot link to `b`.
. When `method` has the annotation {independent}, `v` cannot link to `a`.
. If `a` is of {independent} type (which includes all {e2immutable} types), all its methods are independent; therefore, `v` cannot link to `a`.

It is important to note that the analyser only computes independence for non-modifying methods, so that all methods of implicitly immutable return type are automatically independent.

****
Rule 3: in an assignment `v = new A(b)`, `v` potentially links to `b`.
****

. When the constructor `A` is independent, `v` cannot link to `b`.
. When `b` is of primitive or {e2immutable} type, `v` cannot link to `b`.
. If `A` is {e2immutable}, then `v` cannot link to `b` nor `c`, because all constructors are independent.

Most of the other linking computations are consequences of the basic rules above.
For example,

. in an assignment `v = condition ? a : b`, `v` links to both `a` and `b`.
. type casting does not prevent linking: in `v = (Type)w`, `v` links to `w`
. Binary operators return primitives or `java.lang.String`, which prevents linking: in `v = a + b`, `v` does not link to `a` nor `b`.

****
Rule 4: in an array access `v = a[index]`, `v` links to `a`.
****

Note: links between `b`, `c`, and `d` are possible, but are covered by the {modified} annotation:
when a parameter is {nm}, no modifications at all are possible, not even indirectly.

=== Abstract methods and functional interfaces

Abstract methods are present in interfaces, and abstract classes.
Their very definition is that no implementation is present at the place of definition: only the ins (parameters) and outs (return type) are pre-defined.

Functional interfaces are interfaces with a single abstract method; any other methods in the interface are required to have a `default` implementation.
The following table lists some frequently used ones:

[options=header]
|===

| Name | single abstract method (SAM)
| `Consumer<T>` | `void accept(T t);`
| `Function<T,R>` | `R apply(T t);`
| `BiFunction<T, U, R>` | `R apply(T t, U u);`
| `Supplier<R>` | `R get();`
| `Predicate<T>` | `boolean test(T t);`
|===

It is important not to forget that _any_ interface defining a single abstract method can be seen as a functional interface.
While the examples above all employ generics (more specifically, unbound type parameters), generics are not a requirement for functional interfaces.
The Java language offers syntactic sugar for functional programming, but the types remain abstract Java types.

We will not make any distinction between a functional interface and an abstract type.
If one were forced to make one, the _intention to hold data_ would be the dividing line between a functional interface, which conveys no such intention, and an abstract type, which does.

In this section we want to discuss a limited application of functional interfaces: that where the SAMs have a local implementation.
The general case, where abstract types come in via a parameter, will be taken up in <<higher-level-modifications>>.
Consider the following example:

[source,java]
----
class ApplyLocalFunctions {

    @Container
    static class Counter {
        private int counter;

        @Modified
        public int increment() {
            return ++counter;
        }
    }

    @Modified
    private final Counter myCounter = new Counter();

    @Modified
    private final Supplier<Integer> getAndIncrement = myCounter::increment;

    @Modified
    private final Supplier<Integer> explicitGetAndIncrement = new Supplier<Integer>() {
        @Override @Modified
        public Integer get() {
            return myCounter.increment();
        }
    };

    @Modified
    public int myIncrementer() {
        return getAndIncrement.get();
    }

    @Modified
    public int myExplicitIncrementer() {
        return explicitGetAndIncrement.get();
    }
}
----

The fields `getAndIncrement` and `explicitGetAndIncrement` hold instances of anonymous _inner classes_ of `ApplyLocalFunctions`: these inner classes hold data, they have access to the `myCounter` field.
Their concrete implementations of `get` each modify `myCounter`.
A straightforward application of the rules of modification of fields makes  `getAndIncrement` and `explicitGetAndIncrement` {modified}:
in `myIncrementer`, a modifying method is applied to `getAndIncrement`, and in `myExplicitIncrementer`, a modifying method is applied to `explicitGetAndIncrement`.

Given that `ApplyLocalFunctions` is clearly {e1container}, and the inner classes hold no other data, the inner classes are {e1container} as well.
