== Other annotations

The {e2immu} project defines a whole host of annotations complementary to the ones required for immutability.
We discuss them briefly, and refer to the user manual for an in-depth analysis.

[#nullable-section]
=== Nullable, not null

Nullability is a standard static code analyser topic, which we approach from a computational side: the analyser infers where possible, the user adds annotations to abstract methods.
The complement of not-null (marked {nn}) is nullable (marked {nullable}).

* A method marked {nn} will never return a null result.
This is very standard.
* Calling a parameter marked {nn} will result in a null pointer exception at some point during the object life-cycle.
* A {nn} or {nullable} annotation on a field is a consequence of nullability computations on the assignments to the field.

To be able to compute the nullability of parameters, we must specify some sort of flow or direction to break chicken-and-egg situations.
We compute in the following order:

. context nullability of parameters.
. field nullability
. external nullability of parameters linked to fields

First, we examine the parameter's usage in the method.
Its occurrence in a not-null context directly influences the nullability of the parameter.

==== Higher order nullability

We use the annotation {nn1} to indicate that none of the object's fields can be null.
This concept is useful when working with collections.

Consider the following nullability annotations on the `List` API:

[source,java]
----
boolean add(@NotNull E e);
boolean addAll(@NotNull1 Collection<? extends E> collection);
@NotNull1 static <E> List<E> copyOf(@NotNull1 Collection<? extends E> collection);
@NotNull1 Iterator<E> iterator();
----

They effectively block the use of null elements in the collection.
As a consequence, looping over the elements will not give potential null pointer warnings.

NOTE: This is purely an opinion: we'd rather not use null as elements of a collection.
You are free to annotate differently!

Higher orders are possible as well.
A second level is useful when working with entry sets:

[source,java]
----
V put(@NotNull K key, @NotNull V value);
@NotNull static <K, V> Map<K, V> copyOf(@NotNull Map<? extends K, ? extends V> map);
@NotNull2 Set<Map.Entry<K, V>> entrySet();
----

Note how the map copy is only {nn}, while the entry set is not null, the entries in this set are not null, and the keys and values are neither.

We do not plan to go beyond {nn2}, however.

[#identity-and-fluent]
=== Identity and fluent methods

The analyser marks methods which returns their first parameter with `@Identity`, and methods which return `this` with `@Fluent`.
The former are convenient to introduce preconditions, the latter occur frequently when chaining methods in builders.
Here is an integrated example:

[source,java]
----
@Container(builds=Set.class)
class Builder {
    @NotNull @NotModified @Identity
    private static <T> T requireNonNull(@NotNull T t) {
        if(t == null) throw new UnsupportedOperationException();
        return t;
    }

    private final List<String> list = new ArrayList<>();

    @Fluent
    public Builder add(@NotNull String s) {
        list.add(requireNonNull(s));
        return this;
    }

    @Fluent
    public Builder add(int i) {
        list.add(Integer.toString(i));
        return this;
    }

    @E2Container
    public List<String> build() {
        return List.copyOf(list);
    }

    public static final Set<String> one23 = new Builder().add(1).add(2).add(3).add("go").build();
}
----

[#finalizers]
=== Finalizers

Up to now, we have focused on the distinction between the building phase of an object's life-cycle, and its subsequent immutable phase.
We have ignored the destruction of objects: critically important for some applications, but often completely ignored by Java programmers because of the silent background presence of the garbage collector.
In this section we introduce an annotation, {finalizer}, with the goal of being able to mark that calling a certain method means that the object has reached the end of its life-cycle:

****
Once a method marked {finalizer} has been called, no other methods may be subsequently applied.
****

Why is this useful?
The most obvious use-case for immutability is the meaning of the `build()` method in a builder: can you call it once, or is the builder somehow incremental?

How can the analyser enforce the sequence of method calling on an object?
The simplest way is by some severe restrictions:

****
The following need to be true at all times when using types with finalizer methods:

. Any field of a type with finalizers must be effectively final (marked with {final}).
. A finalizer method can only be called on a field inside a method which is marked as a finalizer as well.
. A finalizer method can never be called on a parameter or any variable linked to it, with linking as defined throughout this document (see <<linking-and-independence>>).
****

Interestingly, these restrictions are such that they help you control the life-cycle of objects with a {finalizer}, by not letting them out of sight.

Let us start from the following example, using <<support-eventuallyfinal>>:

.Example of a type with a finalizer method
[source,java]
----
class ExampleWithFinalizer {
    @BeforeMark
    private final EventuallyFinal<String> data = new EventuallyFinal<>();

    @Fluent
    public ExampleWithFinalizer set(String string) {
        data.setVariable(string);
        return this;
    }

    @Fluent
    public ExampleWithFinalizer doSomething() {
        System.out.println(data.toString());
        return this;
    }

    @Finalizer(contract = true)
    @BeforeMark
    public EventuallyFinal<String> getData() {
        return data;
    }
}
----

Using {fluent} methods to go from construction to finalizer is definitely allowed according to the rules:

[source,java]
----
@E2Container
public static EventuallyFinal<String> fluent() {
    EventuallyFinal<String> d = new ExampleWithFinalizer()
        .set("a").doSomething().set("b").doSomething().getData();
    d.setFinal("x");
    return d;
}
----

Passing on these objects as arguments is permitted, but the recipient should not call the finalizer.
Actually, given our strong preference for containers, the recipient should not even modify the object!
Consider:

[source,java]
----
@E2Container
public static EventuallyFinal<String> stepWise() {
    ExampleWithFinalizer ex = new ExampleWithFinalizer();
    ex.set("a");
    ex.doSomething();
    ex.set("b");
    doSthElse(ex); // <1>
    EventuallyFinal<String> d = ex.getData();
    d.setFinal("x");
    return d;
}

private static void doSthElse(@NotModified ExampleWithFinalizer ex) {
    ex.doSomething(); // <2>
}
----
<1> here we pass on the object
<2> forbidden to call the finalizer; other methods allowed.

Rules 1 and 2 allow you to store a finalizer type inside a field, but only when finalization is attached to the destruction of the holding type.
Examples follow immediately, in the context of the {beforeMark} annotation.

==== Processors and finishers

It is worth observing that finalizers play well with the {beforeMark} annotation.
They allow us to introduce the concepts of _processors_ and _finishers_ for eventually immutable types in their _before_ state.

The purpose of a _processor_ is to receive an object in the {beforeMark} state, hold it, use a lot of temporary data in the meantime, and then release it again, modified but still in the {beforeMark} state.

.Conceptual example of processor
[source,java]
----
class Processor {
    private int count; // <1>

    @BeforeMark // <2>
    private final EventuallyFinal<String> eventuallyFinal;

    public Processor(@BeforeMark EventuallyFinal<String> eventuallyFinal) {
        this.eventuallyFinal = eventuallyFinal;
    }

    public void set(String s) { // <3>
        eventuallyFinal.setVariable(s);
        count++;
    }

    @Finalizer(contract = true)
    @BeforeMark // <4>
    public EventuallyFinal<String> done(String last) {
        eventuallyFinal.setVariable(last + "; tried " + count);
        return eventuallyFinal;
    }
}
----
<1> symbolises the temporary data to be destroyed after processing
<2> the field is private, not passed on, no {mark} method is called on it, and it is exposed only in a {finalizer}
<3> symbolises the modifications that act as processing
<4> the result of processing: an eventually immutable object in the same initial state.

The purpose of a _finisher_ is to receive an object in the {beforeMark} state, and return it in the final state.
In the meantime, it gets modified (finished), while there is other temporary data around.
Once the final state is reached, the analyser guarantees that the temporary data is destroyed by severely limiting the scope of the finisher object.

.Conceptual example of finisher
[source,java]
----
class Finisher {
    private int count; //<1>

    @BeforeMark // <2>
    private final EventuallyFinal<String> eventuallyFinal;

    public Finisher(@BeforeMark EventuallyFinal<String> eventuallyFinal) {
        this.eventuallyFinal = eventuallyFinal;
    }

    @Modified
    public void set(String s) { // <3>
        eventuallyFinal.setVariable(s);
        count++;
    }

    @Finalizer(contract = true)
    @E2Container // <4>
    public EventuallyFinal<String> done(String last) {
        eventuallyFinal.setFinal(last + "; tried " + count);
        return eventuallyFinal;
    }
}
----
<1> symbolises the temporary data to be destroyed.
<2> only possible because the transition occurs in a {finalizer} method
<3> symbolises the modifications that act as finishing
<4> the result of finishing: an eventually immutable object in its end-state.

=== Utility class, extensions, singleton

Using the simple and common definition:

****
*Definition*: a *utility class* is a level 2 immutable class which cannot be instantiated.
****

These definitions imply

. a utility class has no non-static fields,
. it has a single, private, unused constructor,
. and its static fields (if it has any) are sufficiently immutable.

In Java, many classes cannot easily be extended.
Implementations of extensions typically use a utility class with the convention that the first parameter of the static method is the object of the extended method call:

[source,java]
----
@Extension(of=String[].class)
class ExtendString {
    private ExtendString() { throw new UnsupportedOperationException(); }

    public static String weave(@NotModified String[] strings) {
        // generate a new string by weaving the given strings (concat 1st chars, etc.)
    }

    public static int appendEach(@Modified String[] strings, String append) {
        // append the parameter 'append' to each of the strings in the array
    }
}
----

We use the following criteria to designate a utility class as an extension:

****
*Definition*:
****

Static classes can be used to 'extend' closed types, as promoted by the Xtend project.
Level 2 immutable classes can also play the role of extension facilitators, with the additional benefit of having some immutable data to be used as a context.

// ensure a newline at the end
