
== Design and implementation of the plugin

=== Overview

the `JavaAnnotator` class links the plugin to the abstract syntax tree (or PSI in IntelliJ-speak).
It is instrumental to decide which textual elements are to be highlighted.

The annotator is created by the plugin framework on the basis of the `java.xml` configuration file.
It is statically connected to the `JavaConfig` sigleton instance which holds the configuration of the
plugin (which allows you to switch on highlighting of certain annotations, such as:
shall we highlight `@E2final` field types?).

It is also statically connected to the `AnnotationStore` singleton which is responsible for the
assignment of elements to annotations. Elements will be described in a standardized format which will
extend fully qualified type names. Annotations will be described as the simple names of the e2immu annotations.

The annotation store connects to an external server whose address may be changed in the
plugin configuration. By default, it connects to a local instance on http://localhost:8281.
For now, this is a key-value store which keeps track of request and update times.
The protocol is described in <<protocol>>.

The annotation store keeps a cache where elements have a certain TTL. As soon as an element is
not in the cache, its annotation value is requested from the external server.

[#protocol]
=== KV store protocol

[source]
----
# get an annotation name for an element
# curl http://localhost:8281/project-name/element-description
#
# set the annotation name for an element
# curl http://localhost:8281/project-name/element-description/annotation-name
#
# get annotation names for a whole list of elements
# curl -X POST @elements.json http://localhost:8281/project-name/
#
# set the annotation names for a whole map of elements
# curl -X PUT @elementsandannotations.json http://localhost:8281/project-name/
----

The bulk _get_ operation may receive more elements than that it asked for:
depending on the effects of recent _set_ operations, recently updated keys that were asked for
recently may be included as well.

=== Implementation

The plugin's implementation started from the link:https://plugins.jetbrains.com/plugin/13303-return-highlighter[Return
statement highlighter plugin] by Edoardo Luppi.

