
=== The e2immu analyser command line

The input to the analyser is largely controlled by the following primary locations

- `--source=<dir>`: the directories where `.java` sources are to be found.
They can be `:` or `,` separated; the argument can also be repeated.
When nothing is specified, the analyser assumes `src/main/java`.
- `--classpath=<cp>`: the classpath.
This classpath should include the `.class` files corresponding to the `.java` files presented to the analyser.
The format is as parsed by the JDK classpath: colon separated, with wildcards for multipe jar files in the same directory, containing jar files, `.class` files, or directories.
Multiple `--classpath` options may be present; all are concatenated.
When nothing is specified, `build/classes/java/main:build/resources/main` is assumed.
- `--jre=<dir>`: location of the JRE if a different one from the analyser's is to be taken
- `--restrict-source=<packages>`: restrict the input to the following packages.
The parameter can be comma separated, with wildcards as detailed in the note below.

NOTE: The Maven or Gradle plugin typically takes care of correct values for source input and classpath.

Then there are typical options like

- `--quiet` (short `-q`): do not write warnings, errors, etc to the standard output.
They are still uploaded when the `--upload` option is activated.
- `--debug=<logtargets>`: log targets to activate for debug output
- `--ignore-errors`: do not end the analyser in an error state when errors have been raised by the analyser.
They are still uploaded when the `--upload` option is activated.

The following options are available to control the output to the annotation server:

- `--upload` (short: `-u`): upload annotations to an annotation server
- `--upload-url=<url>`, change the default URL which is `http://localhost:8281`
- `--upload-project=<project>`, change the default project which is `default`
- `--upload-packages=<packages>`: a comma-separated list of package names for which annotations are to be uploaded.
The default is to upload all annotations of all types encountered during the parsing process.

The following options are available to control the files written:

- `--write-annotation-xml` (short: `-w`): create annotation files to be included in the resources, and hence the jar of the project.
- `--write-annotation-xml-packages=<packages>`: a comma-separated list of package names for which annotation.xml files are to be written.
The default is to write them for all the packages of `.java` files parsed
- `--write-annotation-xml-dir=<directory>`: alternative location to write the Xml files.
Defaults to the resources directory of the project.
- `--write-annotated-api` (short: `-a`)
- `--write-annotated-api-packages=<packages>`: a comma-separated list of package names for which annotated API files are to be written.
The default is to write them for all the packages of `.java` files parsed
- `--write-annotated-api-dir=<directory>`: alternative location to write the annotated API files.
The default is the main directory of the project

NOTE: When describing packages, a dot at the end of a package name may be used to indicate the inclusion of all sub-packages.
The wildcard `java.` includes `java.lang`, `java.io`, etc.
