== Annotated APIs

=== Preparing an AnnotatedAPI file

Need to speed up.

The analyser's command line interpreter (CLI) provides options for generating a template AnnotatedAPI file from a library.

The following example, taken from the `e2immu/annotation-store` project, contains the Gradle build code to produce a single `IoVertxCore.java` file:

.Part of _build-api.gradle_ in _e2immu/annotation-store_
[source,groovy]
----

plugins {
    id 'java'
}

task runIoVertxAAPI(type: JavaExec) {
    group = "Execution"
    description = "Prepare an AnnotatedAPI file for io.vertx.core"

    classpath = sourceSets.main.runtimeClasspath
    main = 'org.e2immu.analyser.cli.Main'

    Set<File> reducedClassPath = sourceSets.main.runtimeClasspath.toList()
    reducedClassPath += sourceSets.test.runtimeClasspath
    reducedClassPath.removeIf({ f -> f.path.contains("build/classes")
        || f.path.contains("build/resources") })

    args('--classpath=' + reducedClassPath.join(":") + ":jmods/java.base.jmod",
            '-a',
            "--write-annotated-api-packages=io.vertx.core",
            "--source=none",
            "-d=CONFIGURATION,BYTECODE_INSPECTOR")
}
----

The task can be run with the command `./gradlew -b build-api.gradle runIoVertxAAPI`.

=== The file format

AnnotatedAPI files are standard Java files, they will be inspected by a standard Java parser, so all standard syntax rules need to be followed.
They deviate in the following way:

* The primary types become sub-types of a primary type named after the package.
* To ensure that there is no clash with preloaded primary types, they have a dollar `$` suffix.
* A string constant, `PACKAGE_NAME`, specifies the package to which 'dollar types' are transferred.
* All types become classes, all methods return a default value.

.Start of the _JavaUtil.java_ annotated API file
[source,java]
----
public class JavaUtil {
    public static final String PACKAGE_NAME = "java.util";

    static class Enumeration$ {
        boolean hasMoreElements() { return false; }
        E nextElement() { return null; }
        Iterator<E> asIterator() { return null; }
    }

    static class Map$ {
        static class Entry {
            K getKey() { return null; }
            V getValue() { return null; }
    ...
----

=== Annotation types

All {e2immu} annotations have a parameter of the enum type `AnnotationType`, which takes 4 different values:

VERIFY:: this is the default value inserted when parsing Java code.
This corresponds to the standard use of {e2immu} annotations: normally the analyser will compute them for you, but you may want to assert their presence.

VERIFY_ABSENT:: mostly for debugging: insert in the Java code by hand to make sure the analyser does not end up computing this assertion for you.

COMPUTED:: added to annotations inserted by the analyser

CONTRACT:: added to annotations inserted when parsing annotation XMLs or annotated APIs.
This type indicates that a value has not been computed, but stipulated by the user.


