== Concepts

[#concept-modified]
=== Modification

[#concept-containers]
=== Containers

[#concept-linking]
=== Linking and independence

=== Immutability

[#concept-e1immutable]
==== Level 1 immutable

Terminology used:

Variable field:: marked {variable}

Effectively final field:: marked {e1immutable} or {e1container}.

Eventually final field:: marked {e1immutable} or {e1container}, with `after=xxx` parameter

A type is level 1 immutable when all its fields are effectively final.
A type is <<concept-eventual,eventually>> level 1 immutable when after executing a marked method, the fields become effectively final.
This transition is best understood as the removal of a number of methods, marked either {mark} or {only} with parameter `before`, which make the field variable.

[#concept-implicitly-immutable]
==== Implicitly immutable types

Terminology:

Implicitly immutable content:: all the fields of a type which are of implicitly immutable type.

[#concept-e2immutable]
==== Level 2 immutable

A type is level 2 immutable when

. it is level 1 immutable, i.e., all its fields are effectively final
. all fields are not modified
. if a field is not of implicitly immutable type, it must be either private, or level 2 immutable
. all constructors and non-private methods are independent of the fields

A type is <<concept-eventual,eventually>> level 2 immutable when after executing a marked method, the fields become effectively final and or not modified.
This transition is best understood as the removal of a number of methods, marked either {mark} or {only} with parameter `before`, which make the field variable or modify the fields.

[#technical-dynamic-type-annotations]
==== Dynamic type annotations

[#concept-eventual]
=== Eventual immutability

[#concept-higher-order-modification]
=== Higher-order modifications

=== Miscellaneous

[#concept-constant]
==== Constants

Java literals are constants.
An instance of a type whose effectively final fields have only been assigned literal values, is a constant instance.
Typical examples of a constant instances are found in parameterized `enum` fields.

[#concept-statement-time]
==== Statement time

Technically important for variable fields (<<concept-e1immutable>>).

[#concept-singleton]
==== Singleton classes

[#concept-utility-class]
==== Utility classes

A class which is at the same time eventually level 2 immutable, and cannot be instantiated.

The level 2 immutability ensures that the (static) fields are sufficiently immutable.
The fact that it cannot be instantiated is verified by

. the fact that all constructors should be private;
. there should be at least one private constructor;
. no method or field can use the constructors to instantiate objects of this type.

[#concept-extension-class]
==== Extension classes

An extension class is an eventually final type whose static methods all share the same type of first parameter.
