=== List of annotations

For each of the annotations, we answer a couple of standard questions:

Basic:: is this an annotation you definitely should understand?
Immu:: is this annotation part of the immutability concept of the analyzer?
Contract:: will you manually insert this annotation often in interfaces?
Type:: does the annotation occur on types?
Field:: does the annotation occur on (static) fields?
Method:: does the annotation occur on methods and constructors?
Parameter:: does the annotation occur on parameters?

This classification hopefully helps to see the wood for the trees in the long list.

[#allowsInterrupt-annotation]
==== @AllowsInterrupt

|===
| Basic {n} | Immu {n}| Contract {y}| Type {n} | Field {n} | Method {y} | Param {n}
|===

Contract-only annotation indicating that this method or constructor increases the statement time (<<concept-statement-time>>), or allows the execution to be interrupted.

Default value is true.
Methods can be annotated with `@AllowsInterrupt(false)` to explicitly mark that they do not interrupt.

External methods not annotated will not interrupt.

[#beforeMark-annotation]
==== @BeforeMark

|===
| Basic {n} | Immu {y}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary:: Annotation computed when an eventually immutable type is guaranteed to be in its _before_ state, i.e., none of the marked methods have been called yet.
As a dynamic type annotation (<<technical-dynamic-type-annotations>>), it is the opposite of {e1immutable},
{e2immutable}, or its container variants {e1container}, {e2container}.
They guarantee that an eventually immutable object is in its _after_ state, i.e., a marked method has been called and the object has become immutable.

Mode:: not immediately relevant

[#constant-annotation]
==== @Constant

|===
| Basic {n} | Immu {n}| Contract {n}| Type {n} | Field {y} | Method {y} | Param {n}
|===

Summary:: The analyser emits this annotation when a field has a constant final value, or a method returns a constant value.
Its primary purpose is to help debug the analyser.
More details in <<concept-constant>>.

Mode:: This annotation has no opposite.

Example:: In this simple example, an `enum` constant is returned by the `highest` method:

[source,java]
----
@E2Container
public enum Enum_3 {
    ONE(1), TWO(2), THREE(3);

    public final int cnt;

    Enum_3(int cnt) {
        this.cnt = cnt;
    }

    @Constant("THREE")
    public static Enum_3 highest() {
        return THREE;
    }
}
----

[#container-annotation]
==== @Container

|===
| Basic {y} | Immu {y}| Contract {y}| Type {y} | Field {n} | Method {n} | Param {n}
|===

Summary:: The analyser computes this essential annotation for types which do not modify the parameters of their methods.
See <<concept-containers>> for an in-depth discussion.

Mode:: Use this annotation in green mode.
The opposite is {mutableModifiesArguments} if the type has {variable} fields, or {e1immutable} if all the type's fields are effectively final.

Example::
The following examples present containers: <<constant-annotation>>, <<dependent-annotation>>, <<e1container-annotation>>.
Non-containers are in <<e1immutable-annotation>> and <<mutableModifiesArguments-annotation>>.

[#dependent-annotation]
==== @Dependent

|===
| Basic {y} | Immu {y}| Contract {y}| Type {y} | Field {n} | Method {y} | Param {y}
|===

Summary:: Annotation used to indicate that the type's fields <<concept-linking,link>> to the method's parameter or return value, or the constructor's parameters.
This annotation is only present for fields that are not of <<concept-implicitly-immutable,implicitly immutable type>>.
Additionally, on methods, the analyser only computes the annotation when the method is {nm}.

Mode:: Use this annotation in the red mode.
Its opposite is {independent}.

Example::

The assignment of a mutable set to a field typically causes a dependency:

[source,java]
----
class Dependent<String> {
    private final Set<String> set;

    public Dependent(@Dependent Set<String> set) {
        this.set = set;
    }

    @Dependent
    public Set<String> getSet() {
        return set;
    }
}
----

A similar example is in <<e1immutable-annotation>>.

[#dependent1-annotation]
==== @Dependent1

|===
| Basic {n} | Immu {n} | Contract {n}| Type {n} | Field {n} | Method {y} | Param {y}
|===

Summary:: As one of the <<concept-higher-order-modification>> annotations, {dependent1}
on a parameter, of <<concept-implicitly-immutable,implicitly immutable type>>, indicates that this parameter is assigned to one of the fields, or assigned into the object graph of one of the fields.
When computed on a method, the return value of the method, again of implicitly immutable type, is known to be part of the object graph of the fields.

Mode:: This annotation has no opposite.
It implies {independent} because it appears on implicitly immutable types only.

Example:: This annotation has been contracted in many collection-framework methods, such as

[source,java]
----
Collections.add(@Dependent1 E e);

@Dependent1
E List.get(int index);
----

The most direct example explaining the definition is:

[source,java]
----
public class Dependent1_0<T> {
    @Linked1(to = {"Dependent1_0:t"})
    private final T t;

    public Dependent1_0(@Dependent1 T t) {
        this.t = t;
    }

    @Dependent1
    public T getT() {
        return t;
    }
}
----

[#dependent2-annotation]
==== @Dependent2

|===
| Basic {n} | Immu {n} | Contract {n} | Type {n} | Field {n} | Method {y} | Param {y}
|===

Summary:: This annotation is one of the <<concept-higher-order-modification>> annotations.
It is only computed for <<concept-linking,independent>> parameters or methods.
When computed on a parameter, it indicates that part of the <<concept-implicitly-immutable,implicitly immutable content>>
of the argument will be assigned to the fields of the method's type.
When computed on a method, it signifies that part of the implicitly immutable content of the return value is assigned to the fields of the method's type.

This annotation is central to iteration over the implicitly immutable content of a type.

Mode:: This annotation has no opposite.
By definition, implies {independent}.

Example:: This annotation has been contracted in many collection-framework methods, such as

[source,java]
----
boolean Collections.addAll(@Dependent2 Collection<? extends E> coll);

@Dependent2
Stream<E> Collections.stream();
----

[#e1container-annotation]
==== @E1Container

|===
| Basic {y} | Immu {y}| Contract {y}| Type {y} | Field {y} | Method {y} | Param {y}
|===

Summary:: This annotation is a short-hand for the combination of {e1immutable} and {container}, as described in <<concept-e1immutable>> and <<concept-containers>>.

Mode:: This annotation sits in between {mutableModifiesArguments}, {container} and {e2container}.

Example:: In the following example of an eventually level 1 immutable type, the field `j` remains variable until the user of the class calls `setPositiveJ`.

.Example of an eventually @E1Container type
[source,java]
----
@E1Container(after = "j")
class EventuallyE1Immutable_2_M {

    @Modified
    private final Set<Integer> integers = new HashSet<>();

    @Final(after = "j")
    private int j;

    @Modified
    @Only(after = "j")
    public boolean addIfGreater(int i) {
        if (this.j <= 0) throw new UnsupportedOperationException("Not yet set");
        if (i >= this.j) {
            integers.add(i);
            return true;
        }
        return false;
    }

    @NotModified
    public Set<Integer> getIntegers() {
        return integers;
    }

    @NotModified
    public int getJ() {
        return j;
    }

    @Modified
    @Mark("j")
    public void setPositiveJ(int j) {
        if (j <= 0) throw new UnsupportedOperationException();
        if (this.j > 0) throw new UnsupportedOperationException("Already set");

        this.j = j;
    }

    @Modified
    @Only(before = "j")
    public void setNegativeJ(int j) {
        if (j > 0) throw new UnsupportedOperationException();
        if (this.j > 0) throw new UnsupportedOperationException("Already set");
        this.j = j;
    }
}
----

[#e1immutable-annotation]
==== @E1Immutable

|===
| Basic {y} | Immu {y}| Contract {y}| Type {y} | Field {y} | Method {y} | Param {y}
|===

Summary:: This annotation indicates that a type is <<concept-e1immutable,level 1 immutable>>, effectively or eventually, meaning all fields are effectively or eventually final.
Mode:: This annotation sits in between {mutableModifiesArguments} and {e2immutable}.

Example:: The `add` method modifies its parameter `input`; at the same time, the dependence between the constructor's parameter and the field prevents the type from being level 2 immutable:

[source,java]
----
@E1Immutable
class AddToSet {
    private final Set<String> stringsToAdd;

    @Dependent
    public AddToSet(Set<String> set) {
        this.stringsToAdd = set;
    }

    public void add(@Modified @NotNull1 Set<String> input) {
        input.addAll(set);
    }
}
----

[#e2container-annotation]
==== @E2Container

|===
| Basic {y} | Immu {y}| Contract {y}| Type {y} | Field {y} | Method {y} | Param {y}
|===

Summary:: This annotation is a short-hand for the combination of {e2immutable} and {container}, as described in <<concept-e2immutable>> and <<concept-containers>>.

Mode:: This annotation is the default in the red mode.

Example::

[#e2immutable-annotation]
==== @E2Immutable

|===
| Basic {y} | Immu {y}| Contract {y}| Type {y} | Field {y} | Method {y} | Param {y}
|===

Summary:: This annotation indicates that a type is level 2 immutable, effectively or eventually.

Mode:: This annotation is the default in the red mode.
Details:: Level 2 immutability adds extra restrictions on top of level 1 immutability:

. all fields must be not modified;
. all fields of support data types must be either private, or level 2 immutable themselves;
. all non-private methods and constructors must be marked {independent}, i.e.,

.. in the case of constructors, the parameters must not link to the fields of support data types;
.. in the case of methods, neither the return value nor the parameters must link to the fields of support data types.
A consequence of requirement of not modified fields, is that non-private methods cannot be modifying.

[#extensionClass-annotation]
==== @ExtensionClass

|===
| Basic {y} | Immu {n}| Contract {n}| Type {y} | Field {n} | Method {n} | Param {n}
|===

[#final-annotation]
==== @Final

|===
| Basic {y} | Immu {y}| Contract {n}| Type {n} | Field {y} | Method {n} | Param {n}
|===

Summary:: This annotation indicates that a field is effectively or eventually final.
Fields that have the Java modifier `final` possess the annotation, but the analyser does not write it out to avoid clutter.

Mode:: Use this annotation to contract in the green mode, with the opposite, {variable}, being the default.
In the red mode, {final} is the default.

Parameters::
The `after="mark"` parameter indicates that the field is eventually final, after the marking method.

Details:: A field is effectively final when no method, transitively reachable from a non-private non-constructor method, assigns to the field.
A field is eventually final if the above definition holds when one excludes all the methods that are pre-marking, i.e., that hold an annotation `@Only(before="mark")` or `@Mark("mark")`.

Example::
Please find an example of an eventually final field in the example of <<e1container-annotation>>.

.Example for @Variable, @Final
[source,java]
----
@Container
class ExampleManualVariableFinal {

    @Final
    private int i;

    @Variable
    private int j;

    public final int k; // <1>

    public ExampleManualVariableFinal(int p, int q) {
        setI(p);
        this.k = q;
    }

    @NotModified
    public int getI() {
        return i;
    }

    @Modified // <2>
    private void setI(int i) {
        this.i = i;
    }

    @NotModified
    public int getJ() {
        return j;
    }

    @Modified
    public void setJ(int j) {
        this.j = j;
    }
}
----
<.> This field is effectively final, but there is no annotation because of the `final` modifier.
<.> Note that only the constructor accesses this method.

==== @Finalizer

==== @Fluent

|===
| Basic {y} | Immu {n}| Contract {y}| Type {n} | Field {n} | Method {y} | Param {n}
|===

Summary:: This annotation indicates that a method returns `this`.
Mode:: There is no opposite for this annotation.
Details:: Fluent methods do not return a real value.
This is of consequence in the definition of independence for methods, as dependence on `this` is ignored.

==== @Identity

|===
| Basic {y} | Immu {n}| Contract {y}| Type {n} | Field {n} | Method {y} | Param {n}
|===

Summary:: This annotation indicates that a method returns its first parameter.
Mode:: There is no opposite for this annotation.
Details:: Apart for all the obvious consequences, this annotation has an explicit effect on the linking of variables: a method marked {identity} only links to the first parameter.

==== @IgnoreModifications

|===
| Basic {n} | Immu {y}| Contract {y}| Type {n} | Field {y} | Method {n} | Param {n}
|===

Summary:: Helper annotation to mark that modifications on a field are to be ignored, because they fall outside the scope of the application.
Mode:: There is no opposite for this annotation.
It can only be used for contracting, the analyser cannot generate it.
Example:: The only current use is on `System.out` and `System.err`.
The `print` method family is obviously modifying to these fields, however, we judge it to be outside the scope of the application.

==== @Independent

|===
| Basic {y} | Immu {y}| Contract {y}| Type {n} | Field {n} | Method {y} | Param {n}
|===

Summary:: Annotation used to indicate that a method or constructor avoids linking the fields of the type to the return value and parameters.
This annotation is only present when there are support data fields.
Additionally, on methods, the analyser only computes the annotation when the method is {nm}.

Mode:: Use this annotation in the green mode.
Its opposite is {dependent}.

* #TODO# check definition for methods, parameters dependent as well?
* #TODO# why do we ignore dependence on this?

==== @Linked

|===
| Basic {n} | Immu {y}| Contract {n}| Type {n} | Field {y} | Method {n} | Param {n}
|===

Summary:: Annotation to help debug the dependence system.
Mode:: There is no opposite.

==== @Linked1

==== @Mark

|===
| Basic {n} | Immu {y}| Contract {y}| Type {n} | Field {n} | Method {y} | Param {n}
|===

==== @Modified

|===
| Basic {y} | Immu {y}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary:: Core annotation which indicates that content modifications take place.
Mode:: It is the default in the green mode, when {nm} is not present.

==== @Modified1

|===
| Basic {n} | Immu {n}| Contract {n}| Type {y} | Field {n} | Method {n} | Param {y}
|===

Summary:: This annotation is part of the <<higher-level-modifications>>.

Mode:: the opposite annotation is {nm1}.
In green mode, this one is the default; in red mode, {nm1} is the default.

Example:: Applying a c

[#mutableModifiesArguments-annotation]
==== @MutableModifiesArguments

|===
| Basic {y} | Immu {y}| Contract {n}| Type {y} | Field {n} | Method {n} | Param {n}
|===

Summary::
This annotation appears on types which are not a container and not level 1 immutable: at least one method will modify its parameters, and at least one field will be variable.
Definitions are in <<concept-containers>> and <<concept-e1immutable>>.

Mode:: It is the default in the green mode when none of {container}, {e1immutable}, {e1container}, {e2immutable}, {e2container} is present.
Use it for contracting in the red mode.

Example:: Types with non-private fields cannot be level 1 immutable.
Here we combine that with a parameter modifying method:

[source,java]
----
@MutableModifiesArguments
class Mutate {
    @Variable
    public int count;

    public void add(@Modified List<String> list) {
        for(int i=0; i<count; i++) {
            list.add("item "+i);
        }
    }
}
----

==== @NotModified

|===
| Basic {y} | Immu {y}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary:: Core annotation which indicates that no <<concept-modified,modifications>> take place on a field, parameter, or in a method.

Mode:: It is the default in the red mode, when its opposite {modified} is not present.

Example::

[source,java]
----


----

==== @NotModified1

|===
| Basic {n} | Immu {y}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary:: This annotation is part of the <<higher-level-modifications>>.
Contracted to a parameter of an abstract type, it indicates that the abstract method cannot be implemented in a modifying way.
Computed on parameters of any type with <<concept-implicitly-immutable,implicitly immutable content>>, it signifies that


Mode:: It exists only in the green mode; there is no opposite.
It can only be used for contracting, the analyser cannot generate it.

This annotation is a dynamic type annotation on functional types in fields, methods and parameters.
The analyser can compute it in certain circumstances; in other cases, the user can show intent by requesting this property.

Note that because suppliers have no parameters, only modifications to the closure apply.
Functional interfaces are always normally {nm}: there are no modifying methods on them apart from the abstract method.

Example:: We first show an example of a {nm1} contract:

[source,java]
----


----

Here, the analyser computes the annotation:

[source,java]
----


----

==== @NotNull

|===
| Basic {y} | Immu {n}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary:: Core annotation to indicate that a field, parameter, or result of a method can never be `null`.
Mode:: Use this annotation for contracting in the green mode.
It is the opposite of {nullable}.

==== @NotNull1

|===
| Basic {n} | Immu {n}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

==== @NotNull2

|===
| Basic {n} | Immu {n}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

==== @Nullable

|===
| Basic {y} | Immu {n}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary:: This annotation indicates that the field, parameter, or result of a method can be `null`.

Mode:: This is the default in the green mode, when {nn} is not present.
Use it to contract in the red mode.

==== @Only

|===
| Basic {n} | Immu {y}| Contract {y}| Type {n} | Field {n} | Method {y} | Param {n}
|===

==== @PropagateModification

|===
| Basic {n} | Immu {n} | Contract {n}| Type {n} | Field {n} | Method {y} | Param {n}
|===

Summary::
Mode::

==== @Singleton

|===
| Basic {y} | Immu {n}| Contract {n} | Type {y} | Field {n} | Method {n} | Param {n}
|===

Summary:: This annotation indicates that the class is a singleton: only one instance can exist.
Mode:: There is no opposite for this annotation.

==== @TestMark

|===
| Basic {n} | Immu {n}| Contract {y}| Type {n} | Field {y} | Method {y} | Param {y}
|===

Summary::
Mode:: There is no opposite for this annotation.

Details::
xxx

==== @UtilityClass

|===
| Basic {y} | Immu {n}| Contract {n}| Type {y} | Field {n} | Method {n} | Param {n}
|===

Summary:: This annotation indicates that the type is a <<concept-utility-class,utility class>>: its static side is eventually level 2 immutable, and it cannot be instantiated.
As a consequence, should only have static methods.

Mode:: There is no opposite for this annotation.
Details::
The level 2 immutability ensures that the (static) fields are sufficiently immutable.
The fact that it cannot be instantiated is verified by

. the fact that all constructors should be private;
. there should be at least one private constructor;
. no method or field can use the constructors instantiate objects of this type.

==== @Variable

|===
| Basic {y} | Immu {y}| Contract {n} | Type {n} | Field {y} | Method {n} | Param {n}
|===

Summary:: This annotation indicates that a field is not effectively or eventually final, i.e., it is assigned to in methods accessible from non-private non-constructor methods in the type.
Mode:: Use this annotation when contracting in the red mode.
It is the opposite of {final}.
Example:: Please refer to the example of <<final-annotation>>.