== The analyser

=== Inspection

Special naming conventions for creating Java classes that hold annotations and companion methods:

Types:: A sub-type immediately below the primary type in the file can have a dollar at the end.
This indicates that the sub-type becomes a primary type, with the name identical to the sub-type name without the dollar, and the package detailed by a static final field called `PACKAGE_NAME` in the primary type.

Methods:: the rare occasion of adding an annotation to `getClass`, which is final in `java.lang.Object`, requires a dollar at the end which the inspector will remove.

Constructors:: when the type has a $ at the end, the constructor has to follow.
The inspector removes the dollar silently.

Note that the name of the primary type holding the sub-types is completely irrelevant.

=== Analysis

==== Code structure

`PrimaryTypeAnalyser`:

* starts from a `SortedType`, which contains one `PrimaryType` and a list of `WithInspectionAndAnalysis` (methods, fields, sub-types)
* creates and calls `TypeAnalyser`, `MethodAnalyser`, `FieldAnalyser`, and assigns `TypeAnalysis`, `MethodAnalysis`, `FieldAnalysis`
to `TypeInfo.typeAnalysis`, `MethodInfo.methodAnalysis`, `FieldInfo.fieldAnalysis`.

* the `TypeAnalyser` creates, fills, and returns the `TypeAnalysis` object
* the `FieldAnalyser` creates, fills, and returns the `FieldAnalysis` object
* the `MethodAnalyser` creates, fills, and returns the `MethodAnalysis` object, but it also creates:

** `ParameterAnalyser` objects, which fill, create and return `ParameterAnalysis` objects
** `BlockAnalyser` objects, which fill, create and return `StatementAnalysis` objects.
Each `StatementAnalysis` object corresponds recursively to a `Statement` in the `methodBody` block.


`TypeResolution` contains:

* the list of circular dependencies
* the set of implicitly immutable data types for this type

The `TypeAnalysis` object holds:


* a map of constant object flows
* a map of approved preconditions, ready for {mark} and {only}
* annotations and properties via the parent `Analysis` object

`FieldResolution` contains:

* a flag marking if the type is implicitly immutable


The `FieldAnalysis` object holds:

* the object flow of the field
* an effectively final value, which is an instance of `FinalFieldValue` unless we know better; it is not set when the field is {variable}
* a list of variables linked to the field (other fields, parameters)
* a set of internal object flows
* an error map for marking illegal assignments
* an error flag
* annotations and properties via the parent `Analysis` object

`MethodResolution` contains:

* a set of methods of the same type that this method (transitively) calls
* a flag noting whether it is part of construction
* a flag whether it creates an object of itself
* a flag indicating that it only calls static methods


The `MethodAnalysis` object holds:

* a single return value, if available
* summary information about `This` (mostly modification, we can maybe reduce this to single boolean?)
* a list of `StatementAnalysis` objects holding return value information.
#NOTE# we can also store them in the method analyser, there may not be a need to hold on to them.
* a map of variables linked to fields and parameters
* a set of variables linked to the return value(s) of the method
* the joint precondition
* the precondition part for {mark} and {only}
* information about possible {mark} and {only} annotations (can maybe moved directly into the annotations)
* a set of internal object flows
* the object flow of the method
* a fair number of error flags


The `StatementAnalysis` object holds:

* information about the statement: `Statement` reference, parent, next, list of blocks, indices and index
* a flag indicating if the statement (or block represented by the initial statement of the block) ecapes
* a flag indicating that the next statement is never reached
* an error flag
* a precondition represented by this statement
* the state of the method after evaluating this statement
* the precondition of the method after evaluating this statement
* if the statement has an expression part, the value of the expression
* replacement information
* a flag indicating if the method flow reaches the statement
* all variables referenced so far, and their properties (fully incremental)
* dependency information so far

Evaluation of expressions requires an `EvaluationContext` object which moves from statement to statement, applying resulting changes into the `StatementAnalysis` object after each evaluation.
Some of these changes then trickle down to the method analyser which updates the `MethodAnalysis` object.

==== Circular dependencies

The analyser approaches primary types independently, albeit in a carefully computed order of dependency between them.
When it detects a circular dependency between two or more primary types, it issues a warning to indicate that a different, less powerful modification detection algorithm kicks in.
We consider circular dependencies bad programming practice; generally, interfaces can be introduced to remedy this.
The manual modification annotations on the interface method effectively substitute for the assumptions that the less powerful modification algorithm makes.

Inside a primary type, the analyser deals with circular dependencies between the sub-types, the methods and the fields by running multiple iterations.
The main reason it has to do this is that all fields are visible to all sub-types, even if they are marked `private`.

The processing list determines the order in which the analyser processes fields, methods and sub-types.

==== Nested classes

{final}: across all methods in the primary type

Parent or enclosing type when non-static must be have the property as well: {e1immutable}, {e2immutable}, {container}, {independent}.

What to do with abstract superclasses?
They cause a problem because of the abstract methods, which can have any modification status.
#TODO# think and implement.

Eventual?
#TODO# think and implement.

==== Modification of a field

The code executes the following steps:

. Wait until {final} or {variable} has been established.
If {variable}, then the field becomes {modified}.
. If the field is of a functional interface type, the field is {nm} unless we can establish that there is an initializer or unambiguous constructor assignment with an explicit declaration (method reference, lambda, anonymous class implementation).
. As a short-cut, determine that the field is {nm} if its type is level 2 immutable.
Whilst not technically necessary, this short-cut may resolve situations more quickly.
. Wait until the field summaries in methods have been set.
This typically takes exactly one iteration, because a method which reads a field is later in the processing list.
. Wait until modification information is available for those methods which read the field.
Importantly, we consider the methods (and SAM declarations of fields) of all types in the primary type.
. Determine modification based on the modification information in the field summaries.

==== Modification of a method

The code executes the following steps:

. If the method's field summaries contains an assignment to any field, inside the primary type, then the method is {modified}.
. Wait until linking information (and hence modification information on fields) becomes available.
. If any of the field summaries contains a marker for a modified field, then the method becomes {modified}.
The analyser provides these marks when, amongst others, it sees a modifying method call on the field, or the field is an argument to a modifying parameter.
. Next, check the modification status of `this` in `thisSummary`, when the analyser has observed a local method call.
The method is {modified} when the analyser has observed a modification to any of the `this` objects (`super`, ...).
. Then, check the marker for circular method calls or undeclared functional interfaces.
In this situation, the modification status of the method depends on the presence of other modifying methods, non-private fields, on dependent methods.
. Finally, check the marker to copy the modification status from another method.
The analyser issues this marker when the method passes on a functional interface argument to the other method.

==== Condition and state

A method can have restrictions on the parameter and field values called _preconditions_.
In general, these restrictions end up as a boolean expression in `MethodAnalysis.precondition`.
The exception to this rule are the not-null and size restrictions on parameters, which become properties during evaluation, and are written out as separate annotations.

Preconditions that participate in {mark} and {only} are stored in `MethodAnalysis.preconditionForMarkAndOnly`.
They are computed from normal preconditions.

As the analyser progresses through the blocks and statements, it keeps track of:

* the current _condition_, which is the boolean conjunction of all conditions in ever deeper `if` statements, (negated in the `else` block);
* the current _state_, which is the boolean conjunction of all restrictions on variables.

In the condition, top-level disjunctions indicate independent statements, while in the state, top-level conjunctions indicate independent statements:

[source,java]
----
void method1(String a, String b) {
    if(a == null || b == null) {
        // condition and state are: a == null || b == null;
        throw new NullPointerException();
    }
    // state is: a != null && b != null; empty condition
    ...
}
----

In Java, because of short-circuiting, this is functionally identical to the 'independent' form:

[source,java]
----
void method2(String a, String b) {
    if(a == null) {
        // condition and state are: a == null
        throw new NullPointerException();
    }
    // state is: a != null; empty condition
    if(b == null) {
        // condition is: b == null; state is: a != null && b == null
        throw new NullPointerException();
    }
    // state is: a != null && b != null; empty condition
    ...
}
----

Condition and state travel deeper inside the blocks:

[source,java]
----
void method3(String a, String b) {
    if(a == null) {
        // condition and state are: a == null
        if(b == null) {
            // condition and state are: a == null && b == null
            throw new UnsupportedOperationException();
        }
        // condition is: a == null; state is: a == null && b != null
        return;
    }
    // state is: a != null; empty condition
    ...
}
----

Both in `method1` and `method2`, the escape via a runtime exception introduces {nn} annotations on the parameters.
The analyser employs dedicated logic to ensure that in a second pass, it does not flag the condition in the `if` statement as a constant value.
In `method3`, the conjunction in the condition after two successive `if` statements does not allow for individual not-null restrictions.
The result is a precondition, annotated as `@Precondition("(not (null == a) or not (null == b))")`.
Note that, perhaps counter-intuitively, if we were to replace the `return` statement with a `throws` statement, it would have `a == null` as condition, and not `a == null && b != null`.

The rules for adding and removing to condition and state are:

. start the method with the state equal to the preconditions, if applicable;
. when entering a conditional block, start a new `ConditionManager` with the statement's expression added to the current condition and state;
. when a conditional block does not return, add the boolean complement to the state;
. in case of assignments or modifying methods, clear the state (partially);
. the state of parameters and effectively final fields travels up from inside blocks, but only if these blocks are unconditional.
This is most notably the case for a `synchronized` block.

==== Computation of @Mark, @Only

The presence of eventual properties (level 1 immutable, level 2 immutable, content not null, ...) follows from the computation of the {only} and {mark} annotations.
Here, we document how the analyser computes them.

The analyser associates eventuality with a precondition on a field (or technically, on one or more fields); it labels the precondition with a mark string.
Methods that guard against the precondition are _before_ the mark, methods that guard against the boolean complement are _after_ the mark.
We define a guard here as the throwing of a run-time exception when the field's value does not satisfy the condition.

Each method holds information about such a precondition in `SetOnce<MarkAndOnly> markAndOnly`.
The `MethodAnalyser` computes the information in `computeOnlyMarkPrepWork` and `computeOnlyMarkAnnotate`.

Then, the `TypeAnalyser` combines the information of the methods in `analyseOnlyMarkEventuallyE1Immutable`; the end result of the whole computation resides in `SetOnceMap<String, Value> approvedPreconditions` in `TypeAnalysis`.
The keys are the different preconditions that have been approved for eventuality computation, the values are the associated mark strings consisting of the variable names of the fields in the precondition.
Note: the current implementation relies on the precondition to be lifted using an assignment rather than a content change; the code resides in the level 1 immutability check.
As a consequence, it is currently not possible to use the size of a collection, for example, as a precondition.

The eventual annotation will receive a comma-separated list with all the marks in `approvedPreconditions`.

==== Statement analyser

Steps:

. Create local variable (`for(T t: ts)`, assignment statement)
. evaluate initialisers (classic `for`, `try` with resources, normal assignment statements).
The results of the initialisers need to be known to the evaluation context, but cannot be permanent yet.
. evaluate updates (classic `for`).
The results of the updaters need to be known to the evaluation context, but cannot be permanent yet.
. evaluate main expression (many statements).
The results need to be known to the evaluation context.
. specific `return` statement code, update method-level data;
. specific `if`, `switch` code to check evaluations to constant
. primary block, recursive call; merge back by calling `lift`
. sub-blocks, recursive calls; merge back by calling `lift`
. determine state after this statement
. finally, make the results of the evaluation(s) permanent by calling `finalise`

==== Post- and pre-conditions

A non-modifying method without parameters can define an _aspect_ of a type, like `size` or `length`.
We define methods complementary to a normal class or interface method, using the naming convention _method name$action$aspect_.
Let's call them companion methods for now.

Modification+aspect:: for modifying methods, show how the aspect changes from before to after the modification.

Value (+aspect):: compute edge case values, and return the normal value otherwise.
Aspect can be used, but does not have to be present.

Precondition:: describe the precondition in terms of parameters or field values

Invariant:: without aspect present, it has to be a condition on fields which holds all the time.

Invariant+aspect:: this expression describes an invariant of the aspect.
For example, `size >= 0`, before and after any method.

Postcondition:: describe the postcondition of the fields after the modification.
(This is the modification without aspect.)

Transfer (+aspect):: assign state to the return element, transferring it from the current object.

Generate:: generate any other type of

Erase:: we need to think about something that erases state.
A `clear()` method on a collection should remove all `contains(x)` clauses.

Implementation issues:

. Get rid of SIZE and everything surrounding it
. Parsing the methods, and storing them in the type in a reasonable data structure.
We'll work with the evaluated inline-functions; they have a translation mechanism already built in.
. The system generates preconditions, ensure that they can be tested.
. From a companion method we have to translate.

==== Nullity of fields

If the field is effectively final, it receives its values from

. its initialiser
. assignments in the constructor and methods that are exclusively part of the construction phase
. modifying methods cannot change the value, but they can erase constructor information (`instance type X` instead of `new X(...)`)

If the field is variable, there can be assignments in public methods not part of the assignment phase.

Either way, nullity comes from both methods where an assignment take place, and methods where restrictions are placed on the nullity.
The latter can take place in modifying and non-modifying methods.

The statement analyser of the first occurrence of a field in a method introduces a value for the field _only when both the field's value and its nullity are known_.
We need to ensure here that this rule will not be the cause of endless delay loops.

The expected complication is in methods where there is no value yet for the field, but we still expect the nullity of the field variable to be computed.
The field analyser must be able to grab this nullity independently of the value:

* for each method, it needs to know if nullity computations have not been halted.
Typically, this is done in two stages:

==== Loop variables overview

Different situations

. variable defined outside a loop
.. read in the loop, but not assigned in the loop: normal situation
.. assigned in the loop
. variable defined in the loop statement.
Either can be assigned inside the loop as well.
.. `for(String s: strings)`
.. `for(int i=0; i<n; i++)`

`localVariablesAssignedInThisLoop` needs to be frozen before we know the distinction between situations 1 and 2.
As long as the latest assignment is before the loop, the variable in the loop is represented by `var$loop`.
Once we're beyond the assignment, it becomes `var$loop$assigmentId`.

We make no distinction between `forEach` and `for`: in both cases, the variable is added to the `localVariablesAssignedInThisLoop` set.
While we could force the variable to be `final` in the former case, we'll want different versions in case modifying methods are called on them.

In the `forEach` case, we assign a value, once, during the evaluation phase of the loop statement.

==== General property computation

We have decided on a very strict _write once_ system: once a value has been determined, it cannot be changed anymore.
Properties are written in a heavily controlled map of type `VariableProperties`.
The value `Level.DELAY` is never written in the map, as it indicates that no value has been determined yet.

In the statement analyser, property values travel from one statement to the next.
Therefore, the last statement often contains the relevant information for the other analysers to read.

==== Not-null property

Variables in the statement analyser can have not-null induced by the context (parameters in method calls, scope, etc).
At the same time, fields and parameters can get not-null values from the field and parameter analyser.
Combining both in a single, non-incremental value turns out to be impossible.
Therefore, we split, for every variable, non-null in

. `CONTEXT_NOT_NULL`: non-null value induced by context
. `EXTERNAL_NOT_NULL`: non-null value coming from assignments or from external sources
.. from the field analyser: fields
.. from the parameter analyser: parameters
.. assignments in an expression: for fields, local variables, return variable

The combination of the two is the property called `NOT_NULL_VARIABLE`, which can only be read.
It is delayed when one of its components is delayed.

While evaluating expressions, we use the property `NOT_NULL_EXPRESSION`.

The method analyser records the return value's not-null in `NOT_NULL_EXPRESSION`, read from the return variable's `NOT_NULL_VARIABLE`.
The field analyser writes in `EXTERNAL_NOT_NULL`, and reads from the variables' `CONTEXT_NOT_NULL` (when no assignment was made), and the assignment's values' `NOT_NULL_EXPRESSION`.

The parameter analyser maintains the two aspects: context from the statement analyser, and external from the field analyser.

The statement analyser uses the properties `CONTEXT_NOT_NULL_DELAY` and `CONTEXT_NOT_NULL_DELAY_RESOLVED` to control a delay on `CONTEXT_NOT_NULL`, when a method's not-null properties, where the variable occurs as argument, have not been analysed yet.

It is important to record the flow of the properties, and especially the mechanisms to break delays when no information is present.

In the statement analyser:: Let us consider the following cases:
. the variable occurs in the `ChangeData` of `apply` of the main expression: any delays are resolved to `NULLABLE`, when no context not-null delay is present
. the variable does not occur in the `ChangeData`, but is still involved (say the local copy of a variable field `s$0`)

In the field analyser::

In the parameter analyser::
Once a context not-null is known in the statement analyser's last statement, the parameter's value can be set.
Important: this is one-way traffic!
The first statement does NOT copy this value into the 'INITIAL'.
Once a value can come from a field, the parameter analyser will copy it.

==== Modification property

The property indicating modification of a variable has been split in the same way as the not-null property:

. variables in statements use `CONTEXT_MODIFIED` and `MODIFIED_OUTSIDE_METHOD`, summarized in `MODIFIED_VARIABLE`.
. the method's modification status is in `MODIFIED_METHOD`
. a field's modification is in `MODIFIED_OUTSIDE_METHOD`

. modification of `this` is recorded in `METHOD_CALLED`

The statement analyser uses the properties `METHOD_DELAY` and `METHOD_DELAY_RESOLVED` to control a delay on `CONTEXT_MODIFIED`, when a method's modification properties, where the variable occurs as argument or scope, have not been analysed yet.

Again let us record the flow of properties and delay-breaking mechanisms:

In the statement analyser::
. should normally be broken in `MethodLevelData`, compute modification.

In the parameter analyser::
Entirely the same as for the not-null.
