=== Statement analysis

There is one `StatementAnalysis` object per statement, so a method consists of a chain of statements.
All variables that exist in statement _i_ will exist in statement _i+1_ as well.
A method's last statement is the place to find the final value of non-local variables.

Statement analysis is carried out until all statement analysers reach status `DONE`.
A statement analyser _i+1_ cannot reach done unless _i_ is already has reached `DONE`.
Four main aspects control delays in the statement analyser:

. the status of the analyser of the previous statement
. the value of variables
. the linked variable set of variables
. the three expressions in the condition manager: condition, state, pre-condition


=== Variables

We recognize the following types of variables:

* fields, where it is important whether the field is effectively final, variable, or as yet undecided in the first iteration(s)
* parameters, which are non-assignable
* local variables, among which copies of variable fields and versions of variables used in loops but defined outside them
* `this`, `super`
* dependent variables, like the cells in an array; mostly treated as local variables
* one return variable for each method, which is assigned a value in a `return` statement

Some variables never leave the statement analyser(s).
However, there are important information flows:

The method analyser reads

. the fact whether fields have been assigned to help decide on the modification of the method;
. the value of the return variable of the last statement to decide on the method's return value;
. the modification properties of the `this` and `super` variables to help decide on the modification of the method.

The field analyser reads

. almost all information about the fields occurring in the last statement

The parameter analyser reads

. properties of the parameter variables in the last statement
. properties and from the field analyser in case a parameter has been assigned to a field or linked to a field

The statement analyser copies back information

. from the field analyser, about fields occurring in the statement
. from the parameter analyser

It is important to note that there is very limited 'circular' information flow.

Fields are created in the statement analyser only when they occur.
Given the write-once nature of the design, their value remains undecided until the field analyser has decided whether the variable is effectively final or not.
In the latter case, the actual value of a field can change from one statement to the next (or even within statements); this requires additional logic.

Modification and linking is a one-way flow from

. main computation is in the statement analyser
. from the statement analyser to the field analyser: the computation of `CONTEXT_MODIFIED`, closely coupled with the computation of the linked variables of a field variable.
All variables start in the first statement with an empty set of linked variables, and a `Level.FALSE` value for the context modification, unless the user explicitly contracted the modification status of the parameter with an annotation.
. from the field analyser to parameter analyser: in the form of the `MODIFIED_IN_METHOD` property, which ends up combined with `CONTEXT_MODIFIED` into the parameter's final `MODIFIED_VARIABLE` property determining its {modified}/{nm} annotation.

External not-null (ENN) travels from the parameter analyser back to the statement analysers, after values of fields have been established.
Because a statement reaches `DONE` status as soon as value and linked variables have been established, an explicit delay system exists to make sure that statemens which involve fields with a delayed ENN are revisited once.


==== Variable fields

Variable fields interact with synchronisation.
A time increase is equivalent to an opportunity for another thread to update the content of variable fields.

The analyser can determine if a method increases time when called.
Calls to non-private methods always increase time because the user can override them.
Certain statements increase time (`try-catch`, `synchronized`).
The method resolver determines if a method increases time or not.

The statement analyser keeps track of time.
Determining time obviously depends on the methods being called, but because the method resolver determines if a method increases time, this happens in a deterministic way in the first iteration of the analyser.

==== Different variable states

Each statement analyser keeps up to three different states for each variable:

Initial state:: the initial state is either the state as inherited from the previous statement, or the variable's initial state.
The latter situation occurs for every variable introduced in the first statement of each method.

Evaluation state:: the state after evaluation of the main expression of the statement.
Obviously, not all statements have such an expression, or the variable may not occur at all in the expression, in which case the evaluation state can be skipped.

Merge state:: if the statement has sub-blocks, a summary state exists to allow progressing to the next statement.

Information always travels from initial, potentially via evaluation, to merge; never in a different order!
The analyser computes the evaluation of statement _i_ before starting the statement analyser of the sub-blocks, and computes the merge of statement _i_ after all statement analysers in all sub-blocks have been activated.

We use suffixes `-C`, `-E` and `:M` respectively, which means that the following comparisons hold alphanumerically:

----
0-C < 0-E < O.0.0-C < 0.0.0-E < 0.0.0:M < 0.0.1-C < ... < 0:M < 1-C < ...
----

==== Data stored for a variable

The `VariableInfo` objects hold the following data:

Variable:: the variable being stored.
Always present from the start.
Assignment ID:: A marker for when this particular `VariableInfo` object is created.
It contains the statement index, and the level in the container, separated by a colon.
This value is present from the creation of the `VariableInfo` object, even though it can vary across `VariableInfo` objects for the same variable.
Value:: starts off with `NO_VALUE` (not assigned), and becomes immutable when it receives a value.
Linked variables:: start off with `null`, and becomes immutable when it receives a value.
Bar one exception, the linked variables come with the assignment of a value, potentially in a later iteration.
The linked variables of a variable field change when the analyser creates a new local copy for reading, i.e., outside an assignment.
Properties:: a properties map, with `Level.DELAY` being the default value.
Statement time:: a constant `NOT_A_VARIABLE_FIELD` for all non-variable fields.
For fields, starts off with `VARIABLE_FIELD_DELAYED` (not assigned) until we know if the field is variable or not.
Then, for variable fields, it stores the statement time of the latest assignment.
Object flow:: generally also set during an assignment.
The value `NO_FLOW` is used when no value as been set.

All these fields are immutable once they have been set, except the `properties` map, which is incremental.
The `READ` and `ASSIGNED` properties have the following special behaviour: ... #TODO#

==== Tests: Basics_0

[source,java]
----
private final String effectivelyFinal = "abc";
public String getEffectivelyFinal() {
    return effectivelyFinal;
}
----

Analysers:

* Statement analyser, iteration 0, statement 0, return statement.
The field `effectivelyFinal` does not yet exist in the list of variables; the change data yields a `FieldReference` pointing to a value of `NO_VALUE`, and a marker that the variable is read in this statement.

* Method analyser: #TODO#

* Field analyser, iteration 0: it is immediately clear that the field is explicitly final, and that the initialiser is level 2 immutable.
Therefore, an effectively final value can be assigned: `"abc"`.
Everything can be concluded.

* Statement analyser, iteration 1: at initialisation, the variable is created, and the effectively final value is filled.
The main evaluation can therefore return a value.
The return variable can also be set.

* Method analyser: can conclude all except for the approved pre-conditions, which will remain unresolved?

==== Tests: Basics_1

[source,java]
----
public final Set<String> f1;

public Basics_1(Set<String> p0, Set<String> p1, String p2) {
    Set<String> s1 = p0;
    this.f1 = s1;
}

public Set<String> getF1() { return f1; }
----

Iteration 0, statement analyser for the constructor:

* statement 0: at initialisation, `this` and the three parameters are created as variables, in the `INITIAL` phase.
The local variable `s1` is created, and assigned to the first parameter.
Both exist in `EVAL` phase, one with an assignment id, the other with a read id.
* statement 1: a field reference is created, and assigned the value `p0`.
The field is linked to this parameter.

Iteration 0, statement analyser for the getter:
* statement 0: the field does not yet exist in the list of variables.
It is marked as read during evaluation, and will be created during the initialisation step of the next iteration.
The return variable has been created at initialisation, but for now has no value.

Iteration 0, field analyser:

* the field is marked as effectively final.
* because there is no /


Iteration 1, statement analyser for getter:
* the field `f1` has the value `instance type Set<String>`, not linked locally.
* the return variable points to the field `f1`.

IMPORTANT:: We could also return the value of `f1` in the return statement, but at the moment we don't think it matters that much.

Iteration 1, field analyser:
Modification is determined, as is nullability.

Iteration 2: parameter analyser: the `@NotNull` of the field travels to the parameter.

==== Tests: Modification_0

[source,java]
----
public final Set<String> set1 = new HashSet<>();

public void add(@NotNull String v) {
    set1.add(v);
}
----

Iteration 0, statement analyser in `add`, statement 0:
* the expression evaluates to `NO_VALUE` as `set1` is not a known variable

Iteration 0, field analyser:
* the field is explicitly final.
We don't have to wait for modification since the field is public.

Iteration 1, statement analyser in `add`: Value, linked variables, and `@Modified` determined.

