=== Key-value store

The key-value store is a simple, two-class implementation of an independent key-value store acting as a bridge between the {e2immu} analyser and the {intellij} plugin.
It is mostly agnostic to the purpose in the project: it stores key-value pairs in sub-stores called projects.

Unless directed differently by the `e2immu-port` parameter, the store starts listening on port 8281 for HTTP communication.
The protocol summary is:

[source,text]
----
# get an annotation name for an element
# curl http://localhost:8281/v1/get/project-name/element-description
#
# set the annotation name for an element
# curl http://localhost:8281/v1/set/project-name/element-description/annotation-name
#
# get annotation names for a whole list of elements
# curl -X POST @elements.json http://localhost:8281/v1/get/project-name
#
# set the annotation names for a whole map of elements
# curl -X PUT @elementsandannotations.json http://localhost:8281/v1/set/project-name
#
# get all key-value pairs for a project
# curl http://localhost:8281/v1/list/project-name
#
# list all projects
# curl http://localhost:8281/v1/list
----

Projects that do not exist will be created on-demand.
The bulk _get_ operation may receive more elements than that it asked for:
depending on the effects of recent _set_ operations, the store may include recently updated keys that were asked for recently as well.

Start the store by running:
[source,shell script]
----
~/g/e/annotation-store (master)> gradle run

> Task :annotation-store:run
Aug 01, 2020 9:19:55 AM org.e2immu.kvstore.Store
INFO: Started kv server on port 8281; read-within-millis 5000
<=========----> 75% EXECUTING [1m 39s]
> :annotation-store:run
----

In another terminal, experiment with the `curl` statements:
[source,shell script]
----
~> curl http://localhost:8281/v1/get/default/hello
{"hello":""}⏎
~> curl http://localhost:8281/v1/set/default/hello/there
{"updated":1,"ignored":0,"removed":0}⏎
~> curl http://localhost:8281/v1/get/default/hello
{"hello":"there"}⏎
~> curl http://localhost:8281/v1/set/default/its/me
{"updated":1,"ignored":0,"removed":0}⏎
~> curl http://localhost:8281/v1/list/default
{"its":"me","hello":"there"}⏎
~> curl http://localhost:8281/v1/list
{"projects":["default"]}⏎
----

Removing a key-value pair only works via the PUT method:
[source,shell script]
----
~> curl http://localhost:8281/v1/set/default/its/
<html><body><h1>Resource not found</h1></body></html>⏎
~> cat update.json
{"its":"","hello":"here"}
~> curl -X PUT -d @update.json  http://localhost:8281/v1/set/default
{"updated":1,"ignored":0,"removed":1}⏎
~> curl http://localhost:8281/v1/list/default
{"hello":"here"}⏎
----
