=== {intellij} plugin

Without a plugin for an IDE, the analyser would be hard to use, and the main purpose of the project, namely, unobtrusively assisting in better coding, would remain very far off.
The current plugin for {intellij} is absolutely minimal.
We based our initial implementation on the link:https://plugins.jetbrains.com/plugin/13303-return-highlighter[Return statement highlighter plugin^] by Edoardo Luppi.

[#visual-objectives]
==== Visual objectives

For the proof of concept, we aim to color elements of the source code in such a way that there is visual information explaining why a type is not {e2immutable} or {container}.
We propose two schemes, one highlighting the immutable elements, useful when they are sparse, and another one warning for mutable ones in an otherwise pretty immutable environment:

Following the annotation hierarchy for types, we color:

[options=header]
|===
| annotation on type | scheme 1 | scheme 2
| {e2container} (incl. primitives) | green | black
| {e2immutable} | green | black
| {e1container} | orange | orange
| {e1immutable} | orange | orange
| {container} | blue | blue
| {mutable} {modifiesArguments} | black | red
|===

We color the annotation hierarchy for fields as:

[cols="60,20,20",options=header]
|===
| annotation on field | scheme 1 | scheme 2
| {variable}  | black | red
| {modified} | orange | orange
| {nm} | green | black
| {supportData} (when field {nm} and type {e1immutable}) | green italics | black italics
|===

The {supportData} annotation is relevant to understand why a type is not level 2 immutable.
In other situations, it simply clutters.
The analyser will only emit it when the type is already {e1immutable} or {e1container}, and the field is already {nm}.

The plugin transfers dynamic type annotations involving immutability (such as {e2container}) from the field to the type.
As a consequence, the left-hand side `Set` type will color green in:

[source,java]
----
private final Set<String> strings = Set.of("abc", "def");
----

according to the first color scheme.

Methods declarations mix dependency with modification.
Independence is not necessary when there are no support types, and, given that we only start showing support data types when all fields are {nm}, which implies that all methods are {nm}, it makes sense to emit the dependency annotations only in the {nm} situation:

[cols="60,20,20",options=header]
|===
| annotation on method | scheme 1 | scheme 2
| {independent} (implying {nm}) | green |black
| {dependent} (implying {nm}) | orange | orange
| {nm} (no support data) | green | black
| {modified} | black | red
|===

The interesting aspect to constructors is whether they are independent or not.
To be consistent with the system for methods, the analyser will only emit the annotation when the type is showing support data.

[cols="60,20,20",options=header]
|===
| annotation on constructor | scheme 1 | scheme 2
| {independent} (when support data) | green | black
| {dependent} (when support data) | orange | orange
| no support data | black | black
|===

The situation of parameters is binary. The analyser colors the

[options=header]
|===
| annotation on parameter | scheme 1 | scheme 2
| {nm} | green | black
| {modified} | black | red
|===


==== Information flow

Exactly which information does the analyser store in the key-value store?
The keys are type names, method names, parameter names, or field names in a format that both analyser and plugin understand:

* for a type, we use the fully qualified name, with sub-types separated by dots;
* for a method, we use the _distinguishing name_, which is a slightly custom format that looks like
+
type's fully qualified name '.' method name '(' parameter type ',' parameter type ... ')'
+
where the parameter type is 'T#2' or 'M#0' when it is the third type parameter of the method's type, or the first type parameter of the method, respectively.
If the parameter type is not a type parameter, the fully qualified name suffices;

* for a parameter, we append the '#' sign followed by the index to the method's distinguishing name, starting from 0;
* for a field, we use the fully qualified name of the type, a ':', and the name of the field.

The values consist of comma separated annotation type names in lowercase, like _e2immutable,final_.

==== Implementation

The `JavaAnnotator` class links the plugin to the abstract syntax tree (or PSI in IntelliJ-speak).
It is instrumental to decide which textual elements are to be highlighted.

The plugin framework creates the annotator on the basis of the `java.xml` configuration file.
It is statically connected to the `JavaConfig` singleton instance which holds the configuration of the plugin.

It is also statically connected to the `AnnotationStore` singleton which is responsible for the assignment of elements to annotations.
Elements will be described in a standardized format which will extend fully qualified type names.
Annotations will be described as the simple names of the e2immu annotations.

The annotation store connects to an external server whose address is modifiable in the plugin configuration.
By default, it connects to a local instance on http://localhost:8281. For now, this is a key-value store which keeps track of request and update times.

The annotation store keeps a cache where elements have a certain TTL.
As soon as an element is not in the cache, the plugin requests the annotation value from the external server.