:icons: font
:y: icon:check[role="green"]
:n: icon:times[role="red"]

=== Commercial vs open source

All software is Apache 2.0 licensed.
As a consequence, you may use it as you see fit in your commercial projects.

The company provides additional services based on exactly the same software, broadly speaking on three levels:

. we provide the software as a service, so you don't have to host it, upgrade it, resource it, etc.
This service is free for open source projects under the provision that the resulting annotations are part of the "open" aspect of the code.

. we give you access to a larger repository of code, more annotated libraries, than available publicly.
This saves you from having to annotate some libraries yourself.
It also improves the quality of the correct code suggestions.

. we help you leverage the analyser, with two goals in mind:
.. reduce your code base by discovering code duplicates.
Here we would claim that a 10% reduction in "size" should really be possible without
.. upgrade your code base from "old" Java to the latest Java, while tracking latest versions of popular libraries

==== Summary table

The following table summarizes the company's offering:

[cols="7,1,1,1",options="header"]
|===

| Feature | Free | Open Source | Paid

| code analyser, opinionated Java | {y} |  {y} | {y}
| language transforms  | {y} |  {y} | {y}
| libraries: java base | {y} |  {y} | {y}
| duplication checking internally and against common libraries | {y} | {y} | {y}
| correct code suggestions      | {y} |  {y} | {y}
| annotate libraries            | {y} |  {y} | {y}
| IDE support IntelliJ, Eclipse, Visual Studio/Language Server Protocol  | {y} |  {y} | {y}

| cloud infrastructure          | {n} | {y} | {y}
| correct code suggestions by scanning against all contructs in our database  | {n} | {y} | {y}
| library annotation on-demand  | {n} | {n} | {y}
| full single code upgrade      | {n} | {n} | {y}
| multi-year code upgrade care  | {n} | {n} | {y}
| software development | {n}| {n}| {n}
|===

==== In more detail

Cloud infrastructure::
We are running all required tools for you:
. annotation server
. project management app (which annotations, for whom)
. analyser

You just have to install a plugin in your IDE, connect it, configure your project, and edit your build tool or CI/CD configuration.

Code corrections against larger library::
The code to do code corrections is freely available to you.
However, the more 

Library annotations on demand::
Code duplication checking and correct code suggestions work better when all method calls are "known" and have been properly annotated.
Annotation can be made more strict than the code actually warrents, just like we're requiring `java.util.Map` to reject null keys and values.
We can help annotate the libraries you use, be they internal, commercially external or open source.
+
The price can be rather low if we can collaborate on a popular Open Source library which has not been annoted previously, in the understanding the result can be made public.

Full single code upgrade:: You have a working code base in Java, maybe written in the days of Java 1.4? Your youngsters don't like programming 1.4, and are mixing Java Streams and functional programming with old-style Enumerations?
Or are you still using Hibernate 3.5? We believe we can help you there.
+
You provide us with a branch of your code, access to the build scripts and libraries, and we'll do the rest.
We guarantee that green test remain green.
Your code will use modern-style constructs, consistently, and you can choose the preferred writing style.
This service may include upgrades to object relation bridges, but does not normally include SQL modernization.
+
This service assumes that you can provide us with an environment to run all your tests.
Cost will be between linear and quadratic in the amount of lines or statements.
It does not depend on the age of the code base.

Multi-year code upgrade care:: Your Java code is important to you, and you envisage using it for many years to come.
But why investing in developers to upgrade it?
We can keep your code "up to date", so that it makes use of the latest language constructs, uses the latest version of Guava or Spring, runs in the latest Tomcat, etc.
The company will provide yearly or biannual upgrade steps, which they present to you for approval.
Green tests will still run green.
As the update procedure has been mostly automated, albeit still requiring manual control, a full upgrade path can be presented.
We present the new version of the code in a cloud-based development environment like Eclipse Che, using one of the popular build tools.
This allows us to discuss, present, and potentially improve the upgrade in collaboration with your developers.

Software development:: We won't be developing your software!
We're not writing more tests for you.
The company focuses on the analyser and derivative services.
